import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { fr, enUS } from "date-fns/locale";
import type { ClientRevenueData, ClientRevenueSummary } from "@/hooks/useRevenueByClient";

// GestionFlow brand colors
const COLORS = {
  primary: [59, 130, 246] as [number, number, number], // Blue
  dark: [31, 41, 55] as [number, number, number], // Gray-800
  gray: [107, 114, 128] as [number, number, number], // Gray-500
  lightGray: [243, 244, 246] as [number, number, number], // Gray-100
  green: [34, 197, 94] as [number, number, number], // Green
  white: [255, 255, 255] as [number, number, number],
};

export type PlanType = 'free' | 'premium' | 'pro';

interface InvoiceDetail {
  invoice_number: string;
  issue_date: string;
  total: number;
  status: string;
  client_id: string;
}

interface RevenueByClientPdfOptions {
  clientRevenueData: ClientRevenueSummary;
  companyName?: string;
  startDate?: Date;
  endDate?: Date;
  companyFilterName?: string;
  invoiceDetails?: InvoiceDetail[];
  language?: 'fr' | 'en';
  returnBlob?: boolean;
  planType?: PlanType;
  hideBranding?: boolean;
}

const getTranslations = (language: 'fr' | 'en') => {
  return language === 'fr' ? {
    reportTitle: 'Revenus par Client',
    generatedOn: 'Généré le',
    period: 'Période',
    company: 'Entreprise',
    companyFilter: 'Filtre entreprise',
    summary: 'Résumé',
    totalInvoiced: 'Total facturé',
    totalPaid: 'Total encaissé',
    numberOfClients: 'Nombre de clients',
    numberOfInvoices: 'Nombre de factures',
    revenueByClient: 'Revenus par Client',
    clientName: 'Nom du client',
    invoiced: 'Facturé',
    paid: 'Payé',
    invoices: 'Factures',
    percentOfTotal: '% du Total',
    total: 'TOTAL',
    invoiceDetails: 'Détails des Factures par Client',
    invoiceNumber: 'N° Facture',
    issueDate: 'Date d\'émission',
    amount: 'Montant',
    status: 'Statut',
    page: 'Page',
    of: 'sur',
    generatedBy: 'Généré par GestionFlow',
    paid_status: 'Payé',
    sent: 'Envoyé',
    overdue: 'En retard',
    draft: 'Brouillon',
    allPeriods: 'Toutes les périodes',
    since: 'Depuis',
    until: 'Jusqu\'à',
    invoicesFor: 'Factures pour'
  } : {
    reportTitle: 'Revenue by Client',
    generatedOn: 'Generated on',
    period: 'Period',
    company: 'Company',
    companyFilter: 'Company filter',
    summary: 'Summary',
    totalInvoiced: 'Total Invoiced',
    totalPaid: 'Total Paid',
    numberOfClients: 'Number of Clients',
    numberOfInvoices: 'Number of Invoices',
    revenueByClient: 'Revenue by Client',
    clientName: 'Client Name',
    invoiced: 'Invoiced',
    paid: 'Paid',
    invoices: 'Invoices',
    percentOfTotal: '% of Total',
    total: 'TOTAL',
    invoiceDetails: 'Invoice Details by Client',
    invoiceNumber: 'Invoice #',
    issueDate: 'Issue Date',
    amount: 'Amount',
    status: 'Status',
    page: 'Page',
    of: 'of',
    generatedBy: 'Generated by GestionFlow',
    paid_status: 'Paid',
    sent: 'Sent',
    overdue: 'Overdue',
    draft: 'Draft',
    allPeriods: 'All periods',
    since: 'Since',
    until: 'Until',
    invoicesFor: 'Invoices for'
  };
};

export const generateRevenueByClientPdf = async (options: RevenueByClientPdfOptions): Promise<Blob | void> => {
  const {
    clientRevenueData,
    companyName,
    startDate,
    endDate,
    companyFilterName,
    invoiceDetails = [],
    language = 'fr',
    returnBlob = false,
    planType = 'free',
    hideBranding = false,
  } = options;

  const t = getTranslations(language);
  const dateLocale = language === 'fr' ? fr : enUS;
  const currencyLocale = language === 'fr' ? 'fr-CA' : 'en-CA';

  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  let yPosition = margin;
  const totalPages = { value: 1 };

  // Determine branding based on plan
  const showFullBranding = planType === 'free';
  const showDiscreteBranding = planType === 'premium';
  const canHideBranding = planType === 'pro' && hideBranding;

  // Helper function to add footer
  const addFooter = (currentPage: number, total: number) => {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);

    if (!canHideBranding) {
      if (showFullBranding) {
        doc.text(t.generatedBy, margin, pageHeight - 10);
      } else {
        doc.text("GestionFlow", margin, pageHeight - 10);
      }
    }

    doc.text(`${t.page} ${currentPage} ${t.of} ${total}`, pageWidth / 2, pageHeight - 10, { align: 'center' });

    doc.setTextColor(...COLORS.dark);
  };

  // Helper function to format currency
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat(currencyLocale, { style: 'currency', currency: 'CAD' }).format(amount);
  };

  // Helper function to get status label
  const getStatusLabel = (status: string) => {
    const statusMap: Record<string, string> = {
      'paid': t.paid_status,
      'sent': t.sent,
      'overdue': t.overdue,
      'draft': t.draft,
    };
    return statusMap[status] || status;
  };

  // Check for new page
  const checkNewPage = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - 25) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // ===== HEADER SECTION =====
  if (showFullBranding) {
    doc.setFillColor(...COLORS.primary);
    doc.roundedRect(margin, yPosition, 40, 12, 2, 2, 'F');
    doc.setTextColor(...COLORS.white);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("GestionFlow", margin + 20, yPosition + 8, { align: 'center' });
  } else if (showDiscreteBranding || (planType === 'pro' && !hideBranding)) {
    doc.setTextColor(...COLORS.gray);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text("GestionFlow", margin, yPosition + 8);
  }

  // Report title
  doc.setTextColor(...COLORS.dark);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(t.reportTitle, pageWidth - margin, yPosition + 5, { align: 'right' });

  yPosition += 18;

  // Company name
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.dark);

  if (companyName) {
    doc.text(`${t.company}: ${companyName}`, margin, yPosition);
    yPosition += 6;
  }

  // Date range
  let periodText = t.allPeriods;
  if (startDate && endDate) {
    periodText = `${t.period}: ${format(startDate, 'd MMMM yyyy', { locale: dateLocale })} – ${format(endDate, 'd MMMM yyyy', { locale: dateLocale })}`;
  } else if (startDate) {
    periodText = `${t.since} ${format(startDate, 'd MMMM yyyy', { locale: dateLocale })}`;
  } else if (endDate) {
    periodText = `${t.until} ${format(endDate, 'd MMMM yyyy', { locale: dateLocale })}`;
  }
  doc.text(periodText, margin, yPosition);
  yPosition += 6;

  // Company filter
  if (companyFilterName) {
    doc.text(`${t.companyFilter}: ${companyFilterName}`, margin, yPosition);
    yPosition += 6;
  }

  // Generation date
  doc.setTextColor(...COLORS.gray);
  doc.setFontSize(9);
  doc.text(`${t.generatedOn}: ${format(new Date(), 'd MMMM yyyy', { locale: dateLocale })}`, margin, yPosition);

  yPosition += 12;

  // Separator line
  doc.setDrawColor(...COLORS.lightGray);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);

  yPosition += 10;

  // ===== SUMMARY SECTION =====
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text(t.summary, margin, yPosition);
  yPosition += 8;

  // Summary cards - 4 boxes horizontally
  const cardWidth = (contentWidth - 15) / 4;
  const cardHeight = 28;
  const cardPadding = 4;

  const summaryCards = [
    { label: t.totalInvoiced, value: formatCurrency(clientRevenueData.totalRevenue), color: COLORS.primary },
    { label: t.totalPaid, value: formatCurrency(clientRevenueData.totalPaid), color: COLORS.green },
    { label: t.numberOfClients, value: clientRevenueData.clientData.length.toString(), color: COLORS.dark },
    { label: t.numberOfInvoices, value: clientRevenueData.totalInvoices.toString(), color: COLORS.dark }
  ];

  summaryCards.forEach((card, index) => {
    const cardX = margin + (index * (cardWidth + 5));

    doc.setFillColor(...COLORS.lightGray);
    doc.roundedRect(cardX, yPosition, cardWidth, cardHeight, 3, 3, 'F');

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.gray);
    doc.text(card.label, cardX + cardPadding, yPosition + 10);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...card.color);
    doc.text(card.value, cardX + cardPadding, yPosition + 22);
  });

  yPosition += cardHeight + 12;

  // ===== REVENUE BY CLIENT TABLE =====
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text(t.revenueByClient, margin, yPosition);
  yPosition += 8;

  // Prepare table data (sorted by totalInvoiced descending)
  const sortedClients = [...clientRevenueData.clientData].sort((a, b) => b.totalInvoiced - a.totalInvoiced);
  
  const clientTableData = sortedClients.map(client => [
    client.clientName,
    formatCurrency(client.totalInvoiced),
    formatCurrency(client.totalPaid),
    client.invoiceCount.toString(),
    `${client.percentageOfTotal.toFixed(1)}%`
  ]);

  // Add totals row
  clientTableData.push([
    t.total,
    formatCurrency(clientRevenueData.totalRevenue),
    formatCurrency(clientRevenueData.totalPaid),
    clientRevenueData.totalInvoices.toString(),
    '100%'
  ]);

  autoTable(doc, {
    head: [[t.clientName, t.invoiced, t.paid, t.invoices, t.percentOfTotal]],
    body: clientTableData,
    startY: yPosition,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 9,
      cellPadding: 4,
      lineColor: COLORS.lightGray,
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontStyle: 'bold',
      halign: 'left',
    },
    bodyStyles: {
      textColor: COLORS.dark,
    },
    alternateRowStyles: {
      fillColor: [250, 250, 250],
    },
    columnStyles: {
      0: { halign: 'left', cellWidth: 'auto' },
      1: { halign: 'right', cellWidth: 35 },
      2: { halign: 'right', cellWidth: 35 },
      3: { halign: 'center', cellWidth: 25 },
      4: { halign: 'right', cellWidth: 25 },
    },
    didParseCell: (data) => {
      if (data.row.index === clientTableData.length - 1) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = COLORS.lightGray;
      }
    },
    didDrawPage: () => {
      totalPages.value = doc.getNumberOfPages();
    }
  });

  yPosition = (doc as any).lastAutoTable.finalY + 15;

  // ===== INVOICE DETAILS BY CLIENT =====
  if (invoiceDetails.length > 0) {
    // Group invoices by client
    const invoicesByClient = new Map<string, InvoiceDetail[]>();
    
    invoiceDetails.forEach(invoice => {
      const clientId = invoice.client_id;
      if (!invoicesByClient.has(clientId)) {
        invoicesByClient.set(clientId, []);
      }
      invoicesByClient.get(clientId)!.push(invoice);
    });

    // Get status color
    const getStatusColor = (status: string): [number, number, number] => {
      switch (status) {
        case 'paid': return COLORS.green;
        case 'overdue': return [239, 68, 68]; // Red
        case 'sent': return COLORS.primary;
        default: return COLORS.gray;
      }
    };

    // Add invoice details for each client
    for (const client of sortedClients) {
      const clientInvoices = invoicesByClient.get(client.clientId);
      if (!clientInvoices || clientInvoices.length === 0) continue;

      // Check if we need a new page for this client section
      checkNewPage(40);

      // Client header
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.dark);
      doc.text(`${t.invoicesFor} ${client.clientName}`, margin, yPosition);
      yPosition += 6;

      const invoiceTableData = clientInvoices.map(invoice => [
        invoice.invoice_number,
        format(new Date(invoice.issue_date), 'd MMM yyyy', { locale: dateLocale }),
        formatCurrency(invoice.total),
        getStatusLabel(invoice.status)
      ]);

      autoTable(doc, {
        head: [[t.invoiceNumber, t.issueDate, t.amount, t.status]],
        body: invoiceTableData,
        startY: yPosition,
        margin: { left: margin, right: margin },
        styles: {
          fontSize: 8,
          cellPadding: 3,
          lineColor: COLORS.lightGray,
          lineWidth: 0.1,
        },
        headStyles: {
          fillColor: COLORS.gray,
          textColor: COLORS.white,
          fontStyle: 'bold',
          halign: 'left',
        },
        bodyStyles: {
          textColor: COLORS.dark,
        },
        alternateRowStyles: {
          fillColor: [250, 250, 250],
        },
        columnStyles: {
          0: { halign: 'left', cellWidth: 40 },
          1: { halign: 'center', cellWidth: 35 },
          2: { halign: 'right', cellWidth: 40 },
          3: { halign: 'center', cellWidth: 30 },
        },
        didParseCell: (data) => {
          // Color the status column
          if (data.section === 'body' && data.column.index === 3) {
            const status = clientInvoices[data.row.index]?.status;
            if (status) {
              data.cell.styles.textColor = getStatusColor(status);
              data.cell.styles.fontStyle = 'bold';
            }
          }
        },
        didDrawPage: () => {
          totalPages.value = doc.getNumberOfPages();
        }
      });

      yPosition = (doc as any).lastAutoTable.finalY + 10;
    }
  }

  // Update total pages and add footers to all pages
  totalPages.value = doc.getNumberOfPages();

  for (let i = 1; i <= totalPages.value; i++) {
    doc.setPage(i);
    addFooter(i, totalPages.value);
  }

  // Generate filename
  let filename = language === 'fr' ? "rapport-revenus-par-client" : "revenue-by-client-report";
  if (startDate && endDate) {
    filename += `-${format(startDate, 'yyyy-MM-dd')}-${format(endDate, 'yyyy-MM-dd')}`;
  }
  filename += ".pdf";

  if (returnBlob) {
    return doc.output('blob');
  }

  doc.save(filename);
};
