import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { fr, enUS } from "date-fns/locale";

// GestionFlow brand colors
const COLORS = {
  primary: [59, 130, 246] as [number, number, number], // Blue
  dark: [31, 41, 55] as [number, number, number], // Gray-800
  gray: [107, 114, 128] as [number, number, number], // Gray-500
  lightGray: [243, 244, 246] as [number, number, number], // Gray-100
  green: [34, 197, 94] as [number, number, number], // Green
  white: [255, 255, 255] as [number, number, number],
};

export type PlanType = 'free' | 'premium' | 'pro';

export interface StockValueProduct {
  id: string;
  name: string;
  sku?: string | null;
  category?: string | null;
  quantity: number;
  cost: number;
}

export interface StockValueSummary {
  totalInventoryValue: number;
  totalProducts: number;
  totalStockQuantity: number;
  averageCostPerUnit: number;
}

interface StockValuePdfOptions {
  products: StockValueProduct[];
  companyName?: string;
  companyFilterName?: string;
  language?: 'fr' | 'en';
  returnBlob?: boolean;
  planType?: PlanType;
  hideBranding?: boolean;
}

const getTranslations = (language: 'fr' | 'en') => {
  return language === 'fr' ? {
    reportTitle: 'Valeur du Stock',
    generatedOn: 'Généré le',
    company: 'Entreprise',
    companyFilter: 'Filtre entreprise',
    summary: 'Résumé',
    totalInventoryValue: 'Valeur totale du stock',
    totalProducts: 'Nombre de produits',
    totalStockQuantity: 'Quantité totale',
    averageCostPerUnit: 'Coût moyen par unité',
    stockValueTable: 'Détail de la Valeur du Stock',
    productName: 'Produit',
    sku: 'SKU',
    category: 'Catégorie',
    quantity: 'Quantité',
    unitCost: 'Coût unitaire',
    totalValue: 'Valeur totale',
    page: 'Page',
    of: 'sur',
    generatedBy: 'Généré par GestionFlow',
    noData: 'Aucune donnée',
  } : {
    reportTitle: 'Stock Value',
    generatedOn: 'Generated on',
    company: 'Company',
    companyFilter: 'Company filter',
    summary: 'Summary',
    totalInventoryValue: 'Total Inventory Value',
    totalProducts: 'Total Products',
    totalStockQuantity: 'Total Stock Quantity',
    averageCostPerUnit: 'Average Cost per Unit',
    stockValueTable: 'Stock Value Details',
    productName: 'Product',
    sku: 'SKU',
    category: 'Category',
    quantity: 'Quantity',
    unitCost: 'Unit Cost',
    totalValue: 'Total Value',
    page: 'Page',
    of: 'of',
    generatedBy: 'Generated by GestionFlow',
    noData: 'No data',
  };
};

const formatCurrency = (value: number): string => {
  return new Intl.NumberFormat('en-US', { 
    style: 'currency', 
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  }).format(value);
};

export const generateStockValuePdf = async (options: StockValuePdfOptions): Promise<Blob | void> => {
  const {
    products,
    companyName,
    companyFilterName,
    language = 'fr',
    returnBlob = false,
    planType = 'free',
    hideBranding = false,
  } = options;

  const t = getTranslations(language);
  const dateLocale = language === 'fr' ? fr : enUS;

  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  let yPosition = margin;
  const totalPages = { value: 1 };

  // Determine branding based on plan
  const showFullBranding = planType === 'free';
  const showDiscreteBranding = planType === 'premium';
  const canHideBranding = planType === 'pro' && hideBranding;

  // Helper function to add footer
  const addFooter = (currentPage: number, total: number) => {
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);

    if (!canHideBranding) {
      if (showFullBranding) {
        doc.text(t.generatedBy, margin, pageHeight - 10);
      } else {
        doc.text("GestionFlow", margin, pageHeight - 10);
      }
    }

    doc.text(`${t.page} ${currentPage} ${t.of} ${total}`, pageWidth / 2, pageHeight - 10, { align: 'center' });

    doc.setTextColor(...COLORS.dark);
  };

  // Calculate summary stats
  const totalStockQuantity = products.reduce((sum, p) => sum + p.quantity, 0);
  const totalInventoryValue = products.reduce((sum, p) => sum + (p.quantity * p.cost), 0);
  const averageCostPerUnit = totalStockQuantity > 0 ? totalInventoryValue / totalStockQuantity : 0;

  const summary: StockValueSummary = {
    totalInventoryValue,
    totalProducts: products.length,
    totalStockQuantity,
    averageCostPerUnit,
  };

  // Sort products by total value (highest first)
  const sortedProducts = [...products].sort((a, b) => {
    const valueA = a.quantity * a.cost;
    const valueB = b.quantity * b.cost;
    return valueB - valueA;
  });

  // ===== HEADER SECTION =====
  if (showFullBranding) {
    doc.setFillColor(...COLORS.primary);
    doc.roundedRect(margin, yPosition, 40, 12, 2, 2, 'F');
    doc.setTextColor(...COLORS.white);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("GestionFlow", margin + 20, yPosition + 8, { align: 'center' });
  } else if (showDiscreteBranding || (planType === 'pro' && !hideBranding)) {
    doc.setTextColor(...COLORS.gray);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text("GestionFlow", margin, yPosition + 8);
  }

  // Report title
  doc.setTextColor(...COLORS.dark);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(t.reportTitle, pageWidth - margin, yPosition + 5, { align: 'right' });

  yPosition += 18;

  // Company name
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.dark);

  if (companyName) {
    doc.text(`${t.company}: ${companyName}`, margin, yPosition);
    yPosition += 6;
  }

  // Company filter
  if (companyFilterName) {
    doc.text(`${t.companyFilter}: ${companyFilterName}`, margin, yPosition);
    yPosition += 6;
  }

  // Generation date
  doc.setTextColor(...COLORS.gray);
  doc.setFontSize(9);
  doc.text(`${t.generatedOn}: ${format(new Date(), 'd MMMM yyyy', { locale: dateLocale })}`, margin, yPosition);

  yPosition += 12;

  // Separator line
  doc.setDrawColor(...COLORS.lightGray);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);

  yPosition += 10;

  // ===== SUMMARY SECTION =====
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text(t.summary, margin, yPosition);
  yPosition += 8;

  // Summary cards - 4 boxes horizontally
  const cardWidth = (contentWidth - 15) / 4;
  const cardHeight = 28;
  const cardPadding = 4;

  const summaryCards = [
    { label: t.totalInventoryValue, value: formatCurrency(summary.totalInventoryValue), color: COLORS.green },
    { label: t.totalProducts, value: summary.totalProducts.toString(), color: COLORS.dark },
    { label: t.totalStockQuantity, value: summary.totalStockQuantity.toString(), color: COLORS.dark },
    { label: t.averageCostPerUnit, value: formatCurrency(summary.averageCostPerUnit), color: COLORS.dark }
  ];

  summaryCards.forEach((card, index) => {
    const cardX = margin + (index * (cardWidth + 5));

    doc.setFillColor(...COLORS.lightGray);
    doc.roundedRect(cardX, yPosition, cardWidth, cardHeight, 3, 3, 'F');

    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.gray);
    doc.text(card.label, cardX + cardPadding, yPosition + 10);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...card.color);
    doc.text(card.value, cardX + cardPadding, yPosition + 22);
  });

  yPosition += cardHeight + 12;

  // ===== STOCK VALUE TABLE =====
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text(t.stockValueTable, margin, yPosition);
  yPosition += 8;

  // Prepare table data
  const tableData = sortedProducts.map(product => {
    const totalValue = product.quantity * product.cost;
    
    return [
      product.name,
      product.sku || '-',
      product.category || '-',
      product.quantity.toString(),
      formatCurrency(product.cost),
      formatCurrency(totalValue)
    ];
  });

  // Add totals row
  tableData.push([
    language === 'fr' ? 'TOTAL' : 'TOTAL',
    '',
    '',
    summary.totalStockQuantity.toString(),
    '',
    formatCurrency(summary.totalInventoryValue)
  ]);

  autoTable(doc, {
    head: [[t.productName, t.sku, t.category, t.quantity, t.unitCost, t.totalValue]],
    body: tableData,
    startY: yPosition,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 9,
      cellPadding: 4,
      lineColor: COLORS.lightGray,
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: COLORS.primary,
      textColor: COLORS.white,
      fontStyle: 'bold',
      halign: 'left',
    },
    bodyStyles: {
      textColor: COLORS.dark,
    },
    columnStyles: {
      0: { halign: 'left', cellWidth: 'auto' },
      1: { halign: 'left', cellWidth: 25 },
      2: { halign: 'left', cellWidth: 30 },
      3: { halign: 'right', cellWidth: 22 },
      4: { halign: 'right', cellWidth: 28 },
      5: { halign: 'right', cellWidth: 30 },
    },
    didParseCell: (data) => {
      // Style the totals row
      if (data.section === 'body' && data.row.index === tableData.length - 1) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = COLORS.lightGray;
      }
      
      // Style the total value column with green for high values
      if (data.section === 'body' && data.column.index === 5 && data.row.index < tableData.length - 1) {
        const product = sortedProducts[data.row.index];
        if (product) {
          const value = product.quantity * product.cost;
          if (value >= 1000) {
            data.cell.styles.textColor = COLORS.green;
            data.cell.styles.fontStyle = 'bold';
          }
        }
      }
    },
    didDrawPage: () => {
      totalPages.value = doc.getNumberOfPages();
    }
  });

  // Update total pages and add footers to all pages
  totalPages.value = doc.getNumberOfPages();

  for (let i = 1; i <= totalPages.value; i++) {
    doc.setPage(i);
    addFooter(i, totalPages.value);
  }

  // Generate filename
  const filename = language === 'fr' 
    ? `rapport-valeur-stock-${format(new Date(), 'yyyy-MM-dd')}.pdf`
    : `stock-value-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`;

  if (returnBlob) {
    return doc.output('blob');
  }

  doc.save(filename);
};
