project_id = "dkinzkawntfzkabroeib"

[functions.send-email]
verify_jwt = false

[functions.send-subscription-email]
verify_jwt = false

[functions.account-recovery]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.schedule-upgrade]
verify_jwt = false

[functions.upgrade-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-payment-status]
verify_jwt = false

[functions.create-invoice-payment-link]
verify_jwt = false

[functions.send-overdue-reminders]
verify_jwt = false

[functions.encrypt-decrypt]
verify_jwt = false

[functions.migrate-encryption]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.respond-to-quote]
verify_jwt = false

[functions.get-quote-by-token]
verify_jwt = false

[functions.mfa-totp]
verify_jwt = false

[functions.get-all-users]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.scan-receipt]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false

[functions.send-product-update]
verify_jwt = false

[functions.stripe-connect-onboarding]
verify_jwt = false

[functions.stripe-dashboard-link]
verify_jwt = false

[functions.verify-stripe-account]
verify_jwt = false

[functions.reset-stripe-account]
verify_jwt = false

[functions.update-user-plan]
verify_jwt = false
