import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Sidebar Navigation
    "nav.title": "Business Manager",
    "nav.main": "Main",
    "nav.system": "System",
    "nav.dashboard": "Dashboard",
    "nav.companies": "Companies",
    "nav.clients": "Clients",
    "nav.products": "Products & Services",
    "nav.invoices": "Invoices",
    "nav.expenses": "Expenses",
    "nav.reports": "Reports",
    "nav.settings": "Settings",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Overview of your business performance",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.totalRevenue.desc": "From paid invoices",
    "dashboard.activeClients": "Active Clients",
    "dashboard.newThisMonth": "new this month",
    "dashboard.openInvoices": "Open Invoices",
    "dashboard.total": "Total",
    "dashboard.productsServices": "Products/Services",
    "dashboard.activeProducts": "Active products",
    "dashboard.loading": "Loading...",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.recentActivity.desc": "Latest transactions and updates",
    "dashboard.noActivity": "No recent activity",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.quickActions.desc": "Common tasks and shortcuts",
    "dashboard.createInvoice": "Create New Invoice",
    "dashboard.addClient": "Add New Client",
    "dashboard.addProduct": "Add Product/Service",
    "dashboard.viewReports": "View Reports",
    
    // Companies
    "companies.title": "Companies",
    "companies.subtitle": "Manage your business companies and organizations",
    "companies.addButton": "Add Company",
    "companies.loading": "Loading...",
    "companies.dialog.add": "Add New Company",
    "companies.dialog.edit": "Edit Company",
    "companies.dialog.addDesc": "Add a new company to your business management system.",
    "companies.dialog.editDesc": "Update company information.",
    "companies.name": "Company Name",
    "companies.namePlaceholder": "Enter company name",
    "companies.address": "Address",
    "companies.streetAddress": "Street Address",
    "companies.streetPlaceholder": "123 Main Street",
    "companies.city": "City",
    "companies.cityPlaceholder": "City name",
    "companies.provinceState": "Province/State",
    "companies.provinceStatePlaceholder": "Select province/state",
    "companies.postalCode": "Postal Code",
    "companies.postalPlaceholder": "A1A 1A1",
    "companies.country": "Country",
    "companies.countryPlaceholder": "Select country",
    "companies.phone": "Phone",
    "companies.phonePlaceholder": "Enter phone number",
    "companies.email": "Email",
    "companies.emailPlaceholder": "company@example.com",
    "companies.website": "Website",
    "companies.websitePlaceholder": "www.example.com",
    "companies.taxId": "Tax ID",
    "companies.taxIdPlaceholder": "Enter tax ID number",
    "companies.contactPerson": "Contact Person",
    "companies.contactPlaceholder": "Enter contact person name",
    "companies.logo": "Company Logo",
    "companies.uploadLogo": "Upload Logo",
    "companies.currentLogo": "Current Logo",
    "companies.taxes": "Taxes",
    "companies.taxName": "Tax Name",
    "companies.taxNamePlaceholder": "e.g., GST, PST",
    "companies.taxRate": "Tax Rate (%)",
    "companies.taxRatePlaceholder": "0.00",
    "companies.addTax": "Add Tax",
    "companies.invoiceSettings": "Invoice Settings",
    "companies.dueDefault": "Default Due Days",
    "companies.invoicePrefix": "Invoice Number Prefix",
    "companies.invoicePrefixPlaceholder": "INV",
    "companies.invoiceDigits": "Invoice Number Digits",
    "companies.invoiceStart": "Starting Invoice Number",
    "companies.emailTemplates": "Email Templates",
    "companies.invoiceEmailSubject": "Invoice Email Subject",
    "companies.invoiceEmailMessage": "Invoice Email Message",
    "companies.overdueSubject": "Overdue Email Subject",
    "companies.overdueMessage": "Overdue Email Message",
    "companies.paymentSubject": "Payment Confirmation Subject",
    "companies.paymentMessage": "Payment Confirmation Message",
    "companies.cancel": "Cancel",
    "companies.updateButton": "Update Company",
    "companies.addCompany": "Add Company",
    "companies.uploadingLogo": "Uploading logo...",
    "companies.logoError": "Failed to upload logo. Please try again.",
    "companies.delete": "Delete Company",
    "companies.deleteConfirm": "Are you sure you want to delete this company? This action cannot be undone.",
    "companies.deleteButton": "Delete",
    "companies.companyLabel": "Company",
    "companies.websiteLabel": "Website",
    "companies.taxIdLabel": "Tax ID",
    "companies.taxesLabel": "Taxes",
    
    // Clients
    "clients.title": "Clients",
    "clients.subtitle": "Manage your clients and customer relationships",
    "clients.addButton": "Add Client",
    "clients.dialog.add": "Add New Client",
    "clients.dialog.edit": "Edit Client",
    "clients.dialog.addDesc": "Add a new client to your customer database.",
    "clients.dialog.editDesc": "Update client information.",
    "clients.name": "Client Name",
    "clients.namePlaceholder": "Enter client name",
    "clients.contactPerson": "Contact Person",
    "clients.contactPlaceholder": "Enter contact person name",
    "clients.serviceProvider": "Service Provider",
    "clients.serviceProviderPlaceholder": "Select service provider",
    "clients.emails": "Email(s)",
    "clients.emailPlaceholder": "Enter email address",
    "clients.addEmail": "Add Another Email",
    "clients.phone": "Phone",
    "clients.phonePlaceholder": "Enter phone number",
    "clients.address": "Address",
    "clients.addressPlaceholder": "Enter address",
    "clients.language": "Language",
    "clients.languagePlaceholder": "Select language",
    "clients.english": "English",
    "clients.french": "Français",
    "clients.hourlyRate": "Hourly Rate ($)",
    "clients.hourlyRatePlaceholder": "Enter hourly rate",
    "clients.creationDate": "Creation Date",
    "clients.cancel": "Cancel",
    "clients.updateButton": "Update Client",
    "clients.addClient": "Add Client",
    "clients.searchPlaceholder": "Search clients...",
    "clients.listTitle": "Client List",
    "clients.listDesc": "A comprehensive list of all your clients",
    "clients.tableClientName": "Client Name",
    "clients.tableContactPerson": "Contact Person",
    "clients.tableServiceProvider": "Service Provider",
    "clients.tableContactInfo": "Contact Info",
    "clients.tableAddress": "Address",
    "clients.tableLanguage": "Language",
    "clients.tableHourlyRate": "Hourly Rate",
    "clients.tableCreated": "Created",
    "clients.tableActions": "Actions",
    "clients.delete": "Delete Client",
    "clients.deleteConfirm": "Are you sure you want to delete {name}? This action cannot be undone.",
    
    // Products
    "products.title": "Products & Services",
    "products.subtitle": "Manage your products and services catalog",
    "products.addButton": "Add Item",
    "products.dialog.add": "Add New Item",
    "products.dialog.edit": "Edit Item",
    "products.dialog.addDesc": "Add a new product or service to your catalog.",
    "products.dialog.editDesc": "Update product or service information.",
    "products.type": "Type",
    "products.typePlaceholder": "Select type",
    "products.product": "Product",
    "products.service": "Service",
    "products.name": "Name",
    "products.namePlaceholder": "Enter item name",
    "products.description": "Description",
    "products.descPlaceholder": "Enter item description",
    "products.costPrice": "Cost Price",
    "products.salePrice": "Sale Price",
    "products.category": "Category",
    "products.categoryPlaceholder": "Select category",
    "products.quantity": "Quantity",
    "products.quantityPlaceholder": "Enter quantity",
    "products.unit": "Unit",
    "products.unitPlaceholder": "Select unit",
    "products.cancel": "Cancel",
    "products.updateButton": "Update Item",
    "products.addItem": "Add Item",
    "products.searchPlaceholder": "Search products and services...",
    "products.allItems": "All Items",
    "products.products": "Products",
    "products.services": "Services",
    "products.active": "Active",
    "products.inactive": "Inactive",
    "products.salePrice2": "Sale Price",
    "products.cost": "Cost",
    "products.stock": "Stock",
    "products.delete": "Delete",
    "products.deleteConfirm": "Are you sure you want to delete \"{name}\"? This action cannot be undone.",
    
    // Expenses
    "expenses.title": "Expenses",
    "expenses.subtitle": "Track and manage your business expenses",
    "expenses.addButton": "Add Expense",
    "expenses.dialog.add": "Add New Expense",
    "expenses.dialog.edit": "Edit Expense",
    "expenses.dialog.addDesc": "Record a new business expense.",
    "expenses.dialog.editDesc": "Update expense information.",
    "expenses.description": "Description",
    "expenses.descPlaceholder": "Enter expense description",
    "expenses.amount": "Amount",
    "expenses.amountPlaceholder": "0.00",
    "expenses.category": "Category",
    "expenses.categoryPlaceholder": "Select category",
    "expenses.date": "Date",
    "expenses.client": "Client",
    "expenses.clientPlaceholder": "Select client (optional)",
    "expenses.vendor": "Vendor",
    "expenses.vendorPlaceholder": "Enter vendor name",
    "expenses.status": "Status",
    "expenses.statusPlaceholder": "Select status",
    "expenses.notes": "Notes",
    "expenses.notesPlaceholder": "Additional notes...",
    "expenses.cancel": "Cancel",
    "expenses.updateButton": "Update Expense",
    "expenses.addExpense": "Add Expense",
    "expenses.total": "Total Expenses",
    "expenses.paid": "Paid",
    "expenses.unpaid": "Unpaid",
    "expenses.listTitle": "Expense List",
    "expenses.listDesc": "All your business expenses",
    "expenses.tableDescription": "Description",
    "expenses.tableAmount": "Amount",
    "expenses.tableCategory": "Category",
    "expenses.tableDate": "Date",
    "expenses.tableClient": "Client",
    "expenses.tableVendor": "Vendor",
    "expenses.tableStatus": "Status",
    "expenses.tableActions": "Actions",
    "expenses.delete": "Delete Expense",
    "expenses.deleteConfirm": "Are you sure you want to delete this expense? This action cannot be undone.",
    
    // Settings
    "settings.title": "Settings",
    "settings.description": "Manage your account settings",
    "settings.account.title": "Account Information",
    "settings.account.description": "Your personal information",
    "settings.account.email": "Email",
    "settings.appearance.title": "Appearance",
    "settings.appearance.description": "Customize the application appearance according to your preferences",
    "settings.appearance.displayMode": "Display Mode",
    "settings.appearance.light": "Light",
    "settings.appearance.dark": "Dark",
    "settings.appearance.colorTheme": "Color Theme",
    "settings.appearance.classic": "Classic (Blue)",
    "settings.appearance.modern": "Modern (Purple)",
    "settings.appearance.warm": "Warm (Orange)",
    "settings.appearance.nature": "Nature (Green)",
    "settings.language.title": "Language",
    "settings.language.description": "Choose your preferred language",
    "settings.language.english": "English",
    "settings.language.french": "Français",
    
    // Password Change
    "password.title": "Change Password",
    "password.description": "Update your password to secure your account",
    "password.new": "New Password",
    "password.confirm": "Confirm New Password",
    "password.button": "Change Password",
    "password.updating": "Updating...",
    "password.error.length": "New password must be at least 6 characters",
    "password.error.match": "Passwords do not match",
    "password.success.title": "Success",
    "password.success.description": "Your password has been successfully updated.",
    "password.error.title": "Error",
    
    // Auth
    "auth.title": "Business Management",
    "auth.subtitle": "Sign in to your account or create a new one",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signingIn": "Signing in...",
    "auth.displayName": "Display Name",
    "auth.creatingAccount": "Creating account...",
    "auth.createAccount": "Create Account",
    "auth.forgotPassword": "Forgot your password?",
    "auth.signInFailed": "Sign in failed",
    "auth.welcomeBack": "Welcome back!",
    "auth.signInSuccess": "You have successfully signed in.",
    "auth.signUpFailed": "Sign up failed",
    "auth.accountCreated": "Account created!",
    "auth.checkEmail": "Please check your email to verify your account.",
    "auth.displayNameRequired": "Display name is required",
    "auth.resetPassword": "Reset Password",
    "auth.resetPasswordDesc": "Enter your email address and we'll send you a link to reset your password.",
    "auth.resetFailed": "Reset failed",
    "auth.resetEmailSent": "Reset email sent!",
    "auth.checkResetEmail": "Please check your email for reset instructions.",
    "auth.sending": "Sending...",
    "auth.sendResetLink": "Send Reset Link",
    "auth.updatePassword": "Update Password",
    "auth.updatePasswordDesc": "Enter your new password below.",
    "auth.newPassword": "New Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.updating": "Updating...",
    "auth.updateFailed": "Update failed",
    "auth.passwordUpdated": "Password updated!",
    "auth.passwordUpdateSuccess": "Your password has been successfully updated.",
    "auth.passwordsDoNotMatch": "Passwords do not match",
    "auth.passwordTooShort": "Password must be at least 6 characters long",
    "auth.cancel": "Cancel",
  },
  fr: {
    // Sidebar Navigation
    "nav.title": "Gestion d'Entreprise",
    "nav.main": "Principal",
    "nav.system": "Système",
    "nav.dashboard": "Tableau de bord",
    "nav.companies": "Entreprises",
    "nav.clients": "Clients",
    "nav.products": "Produits & Services",
    "nav.invoices": "Factures",
    "nav.expenses": "Dépenses",
    "nav.reports": "Rapports",
    "nav.settings": "Paramètres",
    
    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.subtitle": "Aperçu des performances de votre entreprise",
    "dashboard.totalRevenue": "Revenu total",
    "dashboard.totalRevenue.desc": "Provenant des factures payées",
    "dashboard.activeClients": "Clients actifs",
    "dashboard.newThisMonth": "nouveaux ce mois-ci",
    "dashboard.openInvoices": "Factures ouvertes",
    "dashboard.total": "Total",
    "dashboard.productsServices": "Produits/Services",
    "dashboard.activeProducts": "Produits actifs",
    "dashboard.loading": "Chargement...",
    "dashboard.recentActivity": "Activité récente",
    "dashboard.recentActivity.desc": "Dernières transactions et mises à jour",
    "dashboard.noActivity": "Aucune activité récente",
    "dashboard.quickActions": "Actions rapides",
    "dashboard.quickActions.desc": "Tâches courantes et raccourcis",
    "dashboard.createInvoice": "Créer une nouvelle facture",
    "dashboard.addClient": "Ajouter un nouveau client",
    "dashboard.addProduct": "Ajouter un produit/service",
    "dashboard.viewReports": "Voir les rapports",
    
    // Companies
    "companies.title": "Entreprises",
    "companies.subtitle": "Gérez vos entreprises et organisations",
    "companies.addButton": "Ajouter une entreprise",
    "companies.loading": "Chargement...",
    "companies.dialog.add": "Ajouter une nouvelle entreprise",
    "companies.dialog.edit": "Modifier l'entreprise",
    "companies.dialog.addDesc": "Ajoutez une nouvelle entreprise à votre système de gestion.",
    "companies.dialog.editDesc": "Mettre à jour les informations de l'entreprise.",
    "companies.name": "Nom de l'entreprise",
    "companies.namePlaceholder": "Entrez le nom de l'entreprise",
    "companies.address": "Adresse",
    "companies.streetAddress": "Adresse de rue",
    "companies.streetPlaceholder": "123 rue Principale",
    "companies.city": "Ville",
    "companies.cityPlaceholder": "Nom de la ville",
    "companies.provinceState": "Province/État",
    "companies.provinceStatePlaceholder": "Sélectionnez la province/état",
    "companies.postalCode": "Code postal",
    "companies.postalPlaceholder": "A1A 1A1",
    "companies.country": "Pays",
    "companies.countryPlaceholder": "Sélectionnez le pays",
    "companies.phone": "Téléphone",
    "companies.phonePlaceholder": "Entrez le numéro de téléphone",
    "companies.email": "Email",
    "companies.emailPlaceholder": "entreprise@exemple.com",
    "companies.website": "Site web",
    "companies.websitePlaceholder": "www.exemple.com",
    "companies.taxId": "Numéro fiscal",
    "companies.taxIdPlaceholder": "Entrez le numéro fiscal",
    "companies.contactPerson": "Personne-contact",
    "companies.contactPlaceholder": "Entrez le nom de la personne-contact",
    "companies.logo": "Logo de l'entreprise",
    "companies.uploadLogo": "Télécharger le logo",
    "companies.currentLogo": "Logo actuel",
    "companies.taxes": "Taxes",
    "companies.taxName": "Nom de la taxe",
    "companies.taxNamePlaceholder": "ex: TPS, TVQ",
    "companies.taxRate": "Taux de taxe (%)",
    "companies.taxRatePlaceholder": "0.00",
    "companies.addTax": "Ajouter une taxe",
    "companies.invoiceSettings": "Paramètres de facturation",
    "companies.dueDefault": "Jours d'échéance par défaut",
    "companies.invoicePrefix": "Préfixe de numéro de facture",
    "companies.invoicePrefixPlaceholder": "FACT",
    "companies.invoiceDigits": "Nombre de chiffres de facture",
    "companies.invoiceStart": "Numéro de facture de départ",
    "companies.emailTemplates": "Modèles d'email",
    "companies.invoiceEmailSubject": "Sujet de l'email de facture",
    "companies.invoiceEmailMessage": "Message de l'email de facture",
    "companies.overdueSubject": "Sujet de l'email de retard",
    "companies.overdueMessage": "Message de l'email de retard",
    "companies.paymentSubject": "Sujet de confirmation de paiement",
    "companies.paymentMessage": "Message de confirmation de paiement",
    "companies.cancel": "Annuler",
    "companies.updateButton": "Mettre à jour l'entreprise",
    "companies.addCompany": "Ajouter l'entreprise",
    "companies.uploadingLogo": "Téléchargement du logo...",
    "companies.logoError": "Échec du téléchargement du logo. Veuillez réessayer.",
    "companies.delete": "Supprimer l'entreprise",
    "companies.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cette entreprise ? Cette action ne peut pas être annulée.",
    "companies.deleteButton": "Supprimer",
    "companies.companyLabel": "Entreprise",
    "companies.websiteLabel": "Site web",
    "companies.taxIdLabel": "Numéro fiscal",
    "companies.taxesLabel": "Taxes",
    
    // Clients
    "clients.title": "Clients",
    "clients.subtitle": "Gérez vos clients et relations avec la clientèle",
    "clients.addButton": "Ajouter un client",
    "clients.dialog.add": "Ajouter un nouveau client",
    "clients.dialog.edit": "Modifier le client",
    "clients.dialog.addDesc": "Ajoutez un nouveau client à votre base de données clients.",
    "clients.dialog.editDesc": "Mettre à jour les informations du client.",
    "clients.name": "Nom du client",
    "clients.namePlaceholder": "Entrez le nom du client",
    "clients.contactPerson": "Personne-contact",
    "clients.contactPlaceholder": "Entrez le nom de la personne-contact",
    "clients.serviceProvider": "Fournisseur de services",
    "clients.serviceProviderPlaceholder": "Sélectionnez le fournisseur de services",
    "clients.emails": "Email(s)",
    "clients.emailPlaceholder": "Entrez l'adresse email",
    "clients.addEmail": "Ajouter un autre email",
    "clients.phone": "Téléphone",
    "clients.phonePlaceholder": "Entrez le numéro de téléphone",
    "clients.address": "Adresse",
    "clients.addressPlaceholder": "Entrez l'adresse",
    "clients.language": "Langue",
    "clients.languagePlaceholder": "Sélectionnez la langue",
    "clients.english": "English",
    "clients.french": "Français",
    "clients.hourlyRate": "Taux horaire ($)",
    "clients.hourlyRatePlaceholder": "Entrez le taux horaire",
    "clients.creationDate": "Date de création",
    "clients.cancel": "Annuler",
    "clients.updateButton": "Mettre à jour le client",
    "clients.addClient": "Ajouter le client",
    "clients.searchPlaceholder": "Rechercher des clients...",
    "clients.listTitle": "Liste des clients",
    "clients.listDesc": "Une liste complète de tous vos clients",
    "clients.tableClientName": "Nom du client",
    "clients.tableContactPerson": "Personne-contact",
    "clients.tableServiceProvider": "Fournisseur de services",
    "clients.tableContactInfo": "Coordonnées",
    "clients.tableAddress": "Adresse",
    "clients.tableLanguage": "Langue",
    "clients.tableHourlyRate": "Taux horaire",
    "clients.tableCreated": "Créé",
    "clients.tableActions": "Actions",
    "clients.delete": "Supprimer le client",
    "clients.deleteConfirm": "Êtes-vous sûr de vouloir supprimer {name} ? Cette action ne peut pas être annulée.",
    
    // Products
    "products.title": "Produits & Services",
    "products.subtitle": "Gérez votre catalogue de produits et services",
    "products.addButton": "Ajouter un article",
    "products.dialog.add": "Ajouter un nouvel article",
    "products.dialog.edit": "Modifier l'article",
    "products.dialog.addDesc": "Ajoutez un nouveau produit ou service à votre catalogue.",
    "products.dialog.editDesc": "Mettre à jour les informations du produit ou service.",
    "products.type": "Type",
    "products.typePlaceholder": "Sélectionnez le type",
    "products.product": "Produit",
    "products.service": "Service",
    "products.name": "Nom",
    "products.namePlaceholder": "Entrez le nom de l'article",
    "products.description": "Description",
    "products.descPlaceholder": "Entrez la description de l'article",
    "products.costPrice": "Prix coûtant",
    "products.salePrice": "Prix de vente",
    "products.category": "Catégorie",
    "products.categoryPlaceholder": "Sélectionnez la catégorie",
    "products.quantity": "Quantité",
    "products.quantityPlaceholder": "Entrez la quantité",
    "products.unit": "Unité",
    "products.unitPlaceholder": "Sélectionnez l'unité",
    "products.cancel": "Annuler",
    "products.updateButton": "Mettre à jour l'article",
    "products.addItem": "Ajouter l'article",
    "products.searchPlaceholder": "Rechercher des produits et services...",
    "products.allItems": "Tous les articles",
    "products.products": "Produits",
    "products.services": "Services",
    "products.active": "Actif",
    "products.inactive": "Inactif",
    "products.salePrice2": "Prix de vente",
    "products.cost": "Coût",
    "products.stock": "Stock",
    "products.delete": "Supprimer",
    "products.deleteConfirm": "Êtes-vous sûr de vouloir supprimer \"{name}\" ? Cette action ne peut pas être annulée.",
    
    // Expenses
    "expenses.title": "Dépenses",
    "expenses.subtitle": "Suivez et gérez vos dépenses d'entreprise",
    "expenses.addButton": "Ajouter une dépense",
    "expenses.dialog.add": "Ajouter une nouvelle dépense",
    "expenses.dialog.edit": "Modifier la dépense",
    "expenses.dialog.addDesc": "Enregistrez une nouvelle dépense d'entreprise.",
    "expenses.dialog.editDesc": "Mettre à jour les informations de la dépense.",
    "expenses.description": "Description",
    "expenses.descPlaceholder": "Entrez la description de la dépense",
    "expenses.amount": "Montant",
    "expenses.amountPlaceholder": "0.00",
    "expenses.category": "Catégorie",
    "expenses.categoryPlaceholder": "Sélectionnez la catégorie",
    "expenses.date": "Date",
    "expenses.client": "Client",
    "expenses.clientPlaceholder": "Sélectionnez le client (optionnel)",
    "expenses.vendor": "Fournisseur",
    "expenses.vendorPlaceholder": "Entrez le nom du fournisseur",
    "expenses.status": "Statut",
    "expenses.statusPlaceholder": "Sélectionnez le statut",
    "expenses.notes": "Notes",
    "expenses.notesPlaceholder": "Notes supplémentaires...",
    "expenses.cancel": "Annuler",
    "expenses.updateButton": "Mettre à jour la dépense",
    "expenses.addExpense": "Ajouter la dépense",
    "expenses.total": "Total des dépenses",
    "expenses.paid": "Payé",
    "expenses.unpaid": "Non payé",
    "expenses.listTitle": "Liste des dépenses",
    "expenses.listDesc": "Toutes vos dépenses d'entreprise",
    "expenses.tableDescription": "Description",
    "expenses.tableAmount": "Montant",
    "expenses.tableCategory": "Catégorie",
    "expenses.tableDate": "Date",
    "expenses.tableClient": "Client",
    "expenses.tableVendor": "Fournisseur",
    "expenses.tableStatus": "Statut",
    "expenses.tableActions": "Actions",
    "expenses.delete": "Supprimer la dépense",
    "expenses.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cette dépense ? Cette action ne peut pas être annulée.",
    
    // Settings
    "settings.title": "Paramètres",
    "settings.description": "Gérez les paramètres de votre compte",
    "settings.account.title": "Informations du compte",
    "settings.account.description": "Vos informations personnelles",
    "settings.account.email": "Email",
    "settings.appearance.title": "Apparence",
    "settings.appearance.description": "Personnalisez l'apparence de l'application selon vos préférences",
    "settings.appearance.displayMode": "Mode d'affichage",
    "settings.appearance.light": "Clair",
    "settings.appearance.dark": "Sombre",
    "settings.appearance.colorTheme": "Thème de couleur",
    "settings.appearance.classic": "Classique (Bleu)",
    "settings.appearance.modern": "Moderne (Violet)",
    "settings.appearance.warm": "Chaleureux (Orange)",
    "settings.appearance.nature": "Nature (Vert)",
    "settings.language.title": "Langue",
    "settings.language.description": "Choisissez votre langue préférée",
    "settings.language.english": "English",
    "settings.language.french": "Français",
    
    // Password Change
    "password.title": "Changer le mot de passe",
    "password.description": "Modifiez votre mot de passe pour sécuriser votre compte",
    "password.new": "Nouveau mot de passe",
    "password.confirm": "Confirmer le nouveau mot de passe",
    "password.button": "Changer le mot de passe",
    "password.updating": "Modification en cours...",
    "password.error.length": "Le nouveau mot de passe doit contenir au moins 6 caractères",
    "password.error.match": "Les mots de passe ne correspondent pas",
    "password.success.title": "Succès",
    "password.success.description": "Votre mot de passe a été modifié avec succès.",
    "password.error.title": "Erreur",
    
    // Auth
    "auth.title": "Gestion d'Entreprise",
    "auth.subtitle": "Connectez-vous à votre compte ou créez-en un nouveau",
    "auth.signIn": "Se connecter",
    "auth.signUp": "S'inscrire",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.signingIn": "Connexion en cours...",
    "auth.displayName": "Nom d'affichage",
    "auth.creatingAccount": "Création du compte...",
    "auth.createAccount": "Créer un compte",
    "auth.forgotPassword": "Mot de passe oublié ?",
    "auth.signInFailed": "Échec de la connexion",
    "auth.welcomeBack": "Bon retour !",
    "auth.signInSuccess": "Vous vous êtes connecté avec succès.",
    "auth.signUpFailed": "Échec de l'inscription",
    "auth.accountCreated": "Compte créé !",
    "auth.checkEmail": "Veuillez vérifier votre email pour valider votre compte.",
    "auth.displayNameRequired": "Le nom d'affichage est requis",
    "auth.resetPassword": "Réinitialiser le mot de passe",
    "auth.resetPasswordDesc": "Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.",
    "auth.resetFailed": "Échec de la réinitialisation",
    "auth.resetEmailSent": "Email de réinitialisation envoyé !",
    "auth.checkResetEmail": "Veuillez vérifier votre email pour les instructions de réinitialisation.",
    "auth.sending": "Envoi en cours...",
    "auth.sendResetLink": "Envoyer le lien de réinitialisation",
    "auth.updatePassword": "Mettre à jour le mot de passe",
    "auth.updatePasswordDesc": "Entrez votre nouveau mot de passe ci-dessous.",
    "auth.newPassword": "Nouveau mot de passe",
    "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.updating": "Mise à jour...",
    "auth.updateFailed": "Échec de la mise à jour",
    "auth.passwordUpdated": "Mot de passe mis à jour !",
    "auth.passwordUpdateSuccess": "Votre mot de passe a été mis à jour avec succès.",
    "auth.passwordsDoNotMatch": "Les mots de passe ne correspondent pas",
    "auth.passwordTooShort": "Le mot de passe doit contenir au moins 6 caractères",
    "auth.cancel": "Annuler",
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("app-language") as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "fr")) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
