import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    reports: "Reports",
    reportsDescription: "Business analytics and performance metrics",
    // App Title
    "app.title": "Business Management System",
    // Sidebar Navigation
    "nav.title": "Business Manager",
    "nav.main": "Main",
    "nav.system": "System",
    "nav.dashboard": "Dashboard",
    "nav.companies": "Companies",
    "nav.clients": "Clients",
    "nav.categories": "Categories",
    "nav.products": "Products & Services",
    "nav.stockManagement": "Stock Management",
    "nav.quotes": "Quotes",
    "nav.invoices": "Invoices",
    "nav.timeTracking": "Time Tracking",
    "nav.expenses": "Expenses",
    "nav.reports": "Reports",
    "nav.pricing": "Pricing",
    "nav.settings": "Settings",
    "nav.admin": "Admin",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Overview of your business performance",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.totalRevenue.desc": "From paid invoices",
    "dashboard.activeClients": "Active Clients",
    "dashboard.newThisMonth": "new this month",
    "dashboard.openInvoices": "Open Invoices",
    "dashboard.total": "Total",
    "dashboard.productsServices": "Products/Services",
    "dashboard.activeProducts": "Active products",
    "dashboard.loading": "Loading...",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.recentActivity.desc": "Latest transactions and updates",
    "dashboard.noActivity": "No recent activity",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.quickActions.desc": "Common tasks and shortcuts",
    "dashboard.createInvoice": "Create New Invoice",
    "dashboard.addClient": "Add New Client",
    "dashboard.addProduct": "Add Product/Service",
    "dashboard.viewReports": "View Reports",
    
    // Companies
    "companies.title": "Companies",
    "companies.subtitle": "Manage your business companies and organizations",
    "companies.addButton": "Add Company",
    "companies.loading": "Loading...",
    "companies.dialog.add": "Add New Company",
    "companies.dialog.edit": "Edit Company",
    "companies.dialog.addDesc": "Add a new company to your business management system.",
    "companies.dialog.editDesc": "Update company information.",
    "companies.name": "Company Name",
    "companies.namePlaceholder": "Enter company name",
    "companies.address": "Address",
    "companies.streetAddress": "Street Address",
    "companies.streetPlaceholder": "123 Main Street",
    "companies.city": "City",
    "companies.cityPlaceholder": "City name",
    "companies.provinceState": "Province/State",
    "companies.provinceStatePlaceholder": "Select province/state",
    "companies.postalCode": "Postal Code",
    "companies.postalPlaceholder": "A1A 1A1",
    "companies.country": "Country",
    "companies.countryPlaceholder": "Select country",
    "companies.phone": "Phone",
    "companies.phonePlaceholder": "Enter phone number",
    "companies.email": "Email",
    "companies.emailPlaceholder": "company@example.com",
    "companies.website": "Website",
    "companies.websitePlaceholder": "www.example.com",
    "companies.taxId": "Tax ID",
    "companies.taxIdPlaceholder": "Enter tax ID number",
    "companies.contactPerson": "Contact Person",
    "companies.contactPlaceholder": "Enter contact person name",
    "companies.logo": "Company Logo",
    "companies.uploadLogo": "Upload Logo",
    "companies.currentLogo": "Current Logo",
    "companies.taxes": "Taxes",
    "companies.taxName": "Tax Name",
    "companies.taxNamePlaceholder": "e.g., GST, PST",
    "companies.taxRate": "Tax Rate (%)",
    "companies.taxRatePlaceholder": "0.00",
    "companies.addTax": "Add Tax",
    "companies.invoiceSettings": "Invoice Settings",
    "companies.dueDefault": "Default Due Days",
    "companies.invoicePrefix": "Invoice Number Prefix",
    "companies.invoicePrefixPlaceholder": "INV",
    "companies.invoiceDigits": "Invoice Number Digits",
    "companies.invoiceStart": "Starting Invoice Number",
    "companies.emailTemplates": "Email Templates",
    "companies.invoiceEmailSubject": "Invoice Email Subject",
    "companies.invoiceEmailMessage": "Invoice Email Message",
    "companies.overdueSubject": "Overdue Email Subject",
    "companies.overdueMessage": "Overdue Email Message",
    "companies.paymentSubject": "Payment Confirmation Subject",
    "companies.paymentMessage": "Payment Confirmation Message",
    "companies.invoiceFooter": "Invoice Footer Message",
    "companies.invoiceFooterDesc": "Message displayed at the bottom of all invoices",
    "companies.cancel": "Cancel",
    "companies.updateButton": "Update Company",
    "companies.addCompany": "Add Company",
    "companies.uploadingLogo": "Uploading logo...",
    "companies.logoError": "Failed to upload logo. Please try again.",
    "companies.logoHint": "PNG, JPG, GIF or WEBP (max 2MB)",
    "companies.validation.error": "Validation Error",
    "companies.validation.logoFormatError": "Invalid logo format. Please use PNG, JPG, GIF or WEBP.",
    "companies.validation.logoSizeError": "Logo file is too large. Maximum size is 2MB.",
    "companies.validation.prefixConflict": "Another company already uses this invoice prefix. Please choose a different prefix to avoid invoice number conflicts.",
    "companies.validation.numberConflict": "The invoice numbering configuration would create conflicts with existing invoices: {numbers}. Please adjust the prefix, start number, or digits.",
    "companies.validation.nameRequired": "Company name is required",
    "companies.validation.emailRequired": "Email is required",
    "companies.validation.emailInvalid": "Please enter a valid email address",
    "companies.validation.phoneInvalid": "Please enter a valid phone number (e.g., +1 234 567-8900)",
    "companies.validation.invoicePrefixRequired": "Invoice prefix is required",
    "companies.validation.invoiceDigitsRequired": "Number of digits must be at least 1",
    "companies.validation.invoiceStartNumberRequired": "Start number must be at least 1",
    "companies.delete": "Delete Company",
    "companies.deleteConfirm": "Are you sure you want to delete this company? This action cannot be undone.",
    "companies.deleteButton": "Delete",
    "companies.companyLabel": "Company",
    "companies.websiteLabel": "Website",
    "companies.taxIdLabel": "Tax ID",
    "companies.taxesLabel": "Taxes",
    
    // Clients
    "clients.title": "Clients",
    "clients.subtitle": "Manage your clients and customer relationships",
    "clients.addButton": "Add Client",
    "clients.dialog.add": "Add New Client",
    "clients.dialog.edit": "Edit Client",
    "clients.dialog.addDesc": "Add a new client to your customer database.",
    "clients.dialog.editDesc": "Update client information.",
    "clients.name": "Client Name",
    "clients.namePlaceholder": "Enter client name",
    "clients.contactPerson": "Contact Person",
    "clients.contactPlaceholder": "Enter contact person name",
    "clients.serviceProvider": "Company",
    "clients.serviceProviderPlaceholder": "Select company",
    "clients.emails": "Email(s)",
    "clients.emailPlaceholder": "Enter email address",
    "clients.addEmail": "Add Another Email",
    "clients.phone": "Phone",
    "clients.phonePlaceholder": "Enter phone number",
    "clients.address": "Address",
    "clients.addressPlaceholder": "Enter address",
    "clients.language": "Language",
    "clients.languagePlaceholder": "Select language",
    "clients.english": "English",
    "clients.french": "Français",
    "clients.hourlyRate": "Hourly Rate ($)",
    "clients.hourlyRatePlaceholder": "Enter hourly rate",
    "clients.notes": "Notes",
    "clients.notesPlaceholder": "Enter notes about this client",
    "clients.creationDate": "Creation Date",
    "clients.cancel": "Cancel",
    "clients.updateButton": "Update Client",
    "clients.addClient": "Add Client",
    "clients.searchPlaceholder": "Search clients...",
    "clients.listTitle": "Client List",
    "clients.listDesc": "A comprehensive list of all your clients",
    "clients.tableClientName": "Client Name",
    "clients.tableContactPerson": "Contact Person",
    "clients.tableServiceProvider": "Company",
    "clients.tableContactInfo": "Contact Info",
    "clients.tableAddress": "Address",
    "clients.tableLanguage": "Language",
    "clients.tableHourlyRate": "Hourly Rate",
    "clients.tableCreated": "Created",
    "clients.tableActions": "Actions",
    "clients.delete": "Delete Client",
    "clients.deleteConfirm": "Are you sure you want to delete {name}? This action cannot be undone.",
    "clients.deleteButton": "Delete",
    "clients.validation.error": "Validation Error",
    "clients.validation.companyRequired": "Please select a company",
    "clients.validation.emailRequired": "At least one email is required",
    "clients.validation.emailInvalid": "Please enter a valid email address",
    "clients.validation.phoneInvalid": "Please enter a valid phone number (e.g., +1 234 567-8900)",
    "clients.hourlyPlaceholder": "Enter hourly rate",
    
    // Products
    "products.title": "Products & Services",
    "products.subtitle": "Manage your products and services catalog",
    "products.addButton": "Add Item",
    "products.dialog.add": "Add New Item",
    "products.dialog.edit": "Edit Item",
    "products.dialog.addDesc": "Add a new product or service to your catalog.",
    "products.dialog.editDesc": "Update product or service information.",
    "products.type": "Type",
    "products.typePlaceholder": "Select type",
    "products.product": "Product",
    "products.service": "Service",
    "products.name": "Name",
    "products.namePlaceholder": "Enter item name",
    "products.description": "Description",
    "products.descPlaceholder": "Enter item description",
    "products.costPrice": "Cost Price",
    "products.salePrice": "Sale Price",
    "products.category": "Category",
    "products.categoryPlaceholder": "Select category",
    "products.quantity": "Quantity",
    "products.quantityPlaceholder": "Enter quantity",
    "products.unit": "Unit",
    "products.unitPlaceholder": "Select unit",
    "products.cancel": "Cancel",
    "products.updateButton": "Update Item",
    "products.addItem": "Add Item",
    "products.searchPlaceholder": "Search products and services...",
    "products.allItems": "All Items",
    "products.products": "Products",
    "products.services": "Services",
    "products.active": "Active",
    "products.inactive": "Inactive",
    "products.salePrice2": "Sale Price",
    "products.cost": "Cost",
    "products.stock": "Stock",
    "products.delete": "Delete",
    "products.deleteConfirm": "Are you sure you want to delete \"{name}\"? This action cannot be undone.",
    "products.deleteButton": "Delete",
    "products.catWebDev": "Web Development",
    "products.catMobileDev": "Mobile Development",
    "products.catSoftware": "Software",
    "products.catConsulting": "Consulting",
    "products.catHardware": "Hardware",
    "products.catDesign": "Design",
    "products.catMarketing": "Marketing",
    "products.catTraining": "Training",
    "products.catSupport": "Support",
    "products.catMaintenance": "Maintenance",
    "products.catHosting": "Hosting",
    "products.catCloudServices": "Cloud Services",
    "products.catSecurity": "Security",
    "products.catDataAnalysis": "Data Analysis",
    "products.catContentCreation": "Content Creation",
    "products.catPhotography": "Photography",
    "products.catVideoProduction": "Video Production",
    "products.catTranslation": "Translation",
    "products.catLegalServices": "Legal Services",
    "products.catAccounting": "Accounting",
    "products.catOther": "Other",
    "products.unitPiece": "Piece",
    "products.unitHour": "Hour",
    "products.unitDay": "Day",
    "products.unitMonth": "Month",
    "products.unitYear": "Year",
    
    // Invoices
    "invoices.title": "Invoices",
    "invoices.subtitle": "Create and manage your invoices",
    "invoices.createButton": "Create Invoice",
    "invoices.dialog.edit": "Edit Invoice",
    "invoices.dialog.create": "Create New Invoice",
    "invoices.dialog.editDesc": "Update invoice information.",
    "invoices.dialog.createDesc": "Create a new invoice with multiple products or services.",
    "invoices.selectCompany": "Select Company",
    "invoices.companyPlaceholder": "Select company",
    "invoices.selectClient": "Select Client",
    "invoices.clientPlaceholder": "Select client",
    "invoices.clientPlaceholderNoCompany": "Select company first",
    "invoices.issueDate": "Issue Date",
    "invoices.dueDate": "Due Date",
    "invoices.terms": "Terms",
    "invoices.termsPlaceholder": "Payment terms",
    "invoices.notes": "Notes",
    "invoices.notesPlaceholder": "Additional notes",
    "invoices.addItems": "Add Items",
    "invoices.selectProduct": "Select Product/Service (optional)",
    "invoices.productPlaceholder": "Select existing product/service or enter custom",
    "invoices.customItem": "Custom Item",
    "invoices.addNewProduct": "Add New Product/Service",
    "invoices.description": "Description",
    "invoices.descPlaceholder": "Item description",
    "invoices.quantity": "Quantity",
    "invoices.unitPrice": "Unit Price",
    "invoices.itemNotes": "Notes (optional)",
    "invoices.itemNotesPlaceholder": "Item notes",
    "invoices.addItemButton": "Add Item",
    "invoices.updateItem": "Update Item",
    "invoices.invoiceItems": "Invoice Items",
    "invoices.total": "Total",
    "invoices.remove": "Remove",
    "invoices.subtotal": "Subtotal",
    "invoices.taxAmount": "Tax Amount",
    "invoices.totalAmount": "Total Amount",
    "invoices.cancel": "Cancel",
    "invoices.saveInvoice": "Save Invoice",
    "invoices.updateInvoice": "Update Invoice",
    "invoices.loading": "Loading...",
    "invoices.filterByStatus": "Filter by Status",
    "invoices.statusAll": "All Statuses",
    "invoices.statusDraft": "Draft",
    "invoices.statusSent": "Sent",
    "invoices.statusPaid": "Paid",
    "invoices.statusOverdue": "Overdue",
    "invoices.filterByClient": "Filter by Client",
    "invoices.clientAll": "All Clients",
    "invoices.filterByCompany": "Filter by Company",
    "invoices.companyAll": "All Companies",
    "invoices.archiveButton": "Archive",
    "invoices.unarchiveButton": "Unarchive",
    "invoices.archived": "Archived",
    "invoices.showArchived": "Archived invoices",
    "invoices.showActive": "Active invoices",
    "invoices.listTitle": "Invoice List",
    "invoices.listDesc": "Manage all your invoices in one place",
    "invoices.tableInvoiceNumber": "Invoice #",
    "invoices.tableClient": "Client",
    "invoices.tableAmount": "Amount",
    "invoices.tableStatus": "Status",
    "invoices.tableIssueDate": "Issue Date",
    "invoices.tableDueDate": "Due Date",
    "invoices.tableItems": "Items",
    "invoices.tableActions": "Actions",
    "invoices.delete": "Delete Invoice",
    "invoices.deleteConfirm": "Are you sure you want to delete invoice {number}? This action cannot be undone.",
    "invoices.deleteButton": "Delete",
    "invoices.emailDialog.title": "Send Invoice Email",
    "invoices.emailDialog.desc": "Choose email type and customize the message before sending",
    "invoices.emailType": "Email Type",
    "invoices.emailTypeNew": "New Invoice",
    "invoices.emailTypeOverdue": "Overdue Payment Reminder",
    "invoices.emailTypeConfirmation": "Payment Confirmation",
    "invoices.emailClient": "Client:",
    "invoices.emailInvoice": "Invoice:",
    "invoices.emailRecipients": "Select Email Recipients",
    "invoices.emailNoEmails": "No email addresses found for this client",
    "invoices.emailCC": "CC (Optional)",
    "invoices.emailCCPlaceholder": "Enter CC email address",
    "invoices.emailAddCC": "Add CC Email",
    "invoices.emailSubject": "Email Subject",
    "invoices.emailSubjectPlaceholder": "Email subject",
    "invoices.emailMessage": "Email Message",
    "invoices.emailMessagePlaceholder": "Email message",
    "invoices.emailPlaceholders": "Available placeholders: {client_name}, {invoice_number}, {issue_date}, {due_date}, {total}, {company_name}, {days_overdue}",
    "invoices.sendEmail": "Send Email",
    "invoices.sending": "Sending...",
    "invoices.totalInvoices": "Total Invoices",
    "invoices.totalAmountLabel": "Total Amount",
    "invoices.paidAmount": "Paid Amount",
    "invoices.outstanding": "Outstanding",
    "invoices.searchPlaceholder": "Search invoices...",
    "invoices.filterBy": "Filter by",
    "invoices.allInvoices": "All Invoices",
    "invoices.byClient": "By Client",
    "invoices.byCompany": "By Company",
    
    // Expenses
    "expenses.title": "Expenses",
    "expenses.subtitle": "Track and manage your business expenses",
    "expenses.addButton": "Add Expense",
    "expenses.dialog.add": "Add New Expense",
    "expenses.dialog.edit": "Edit Expense",
    "expenses.dialog.addDesc": "Record a new business expense.",
    "expenses.dialog.editDesc": "Update expense information.",
    "expenses.description": "Description",
    "expenses.descPlaceholder": "Enter expense description",
    "expenses.amount": "Amount",
    "expenses.amountPlaceholder": "0.00",
    "expenses.category": "Category",
    "expenses.categoryPlaceholder": "Select category",
    "expenses.date": "Date",
    "expenses.company": "Company",
    "expenses.companyPlaceholder": "Select company (optional)",
    "expenses.vendor": "Vendor",
    "expenses.vendorPlaceholder": "Enter vendor name",
    "expenses.status": "Status",
    "expenses.statusPlaceholder": "Select status",
    "expenses.notes": "Notes",
    "expenses.notesPlaceholder": "Additional notes...",
    "expenses.cancel": "Cancel",
    "expenses.updateButton": "Update Expense",
    "expenses.addExpense": "Add Expense",
    "expenses.total": "Total Expenses",
    "expenses.paid": "Paid",
    "expenses.unpaid": "Unpaid",
    "expenses.listTitle": "Expense List",
    "expenses.listDesc": "All your business expenses",
    "expenses.tableDescription": "Description",
    "expenses.tableAmount": "Amount",
    "expenses.tableCategory": "Category",
    "expenses.tableDate": "Date",
    "expenses.tableClient": "Client",
    "expenses.tableVendor": "Vendor",
    "expenses.tableStatus": "Status",
    "expenses.tableActions": "Actions",
    "expenses.delete": "Delete Expense",
    "expenses.deleteConfirm": "Are you sure you want to delete this expense? This action cannot be undone.",
    "expenses.loading": "Loading...",
    "expenses.categories.Office": "Office",
    "expenses.categories.Meals": "Meals",
    "expenses.categories.Travel": "Travel",
    "expenses.categories.Software": "Software",
    "expenses.categories.Marketing": "Marketing",
    "expenses.categories.Utilities": "Utilities",
    "expenses.categories.Products": "Products",
    "expenses.categories.Other": "Other",
    
    // Reports
    "reports.title": "Reports",
    "reports.subtitle": "Financial reports and analysis",
    "reports.tabs.overview": "Overview",
    "reports.tabs.revenue": "Revenue",
    "reports.tabs.products": "Stock",
    "reports.tabs.expenses": "Expenses",
    "reports.tabs.clients": "Clients",
    "reports.tabs.taxes": "Taxes",
    "reports.tabs.invoices": "Invoices",
    "reports.invoices.listTitle": "Invoice List",
    "reports.invoices.listDesc": "{count} invoice(s) found",
    "reports.invoices.grandTotal": "Grand Total",
    "reports.invoices.filterByStatus": "Filter by status ({count})",
    "reports.invoices.allStatuses": "All",
    "reports.invoices.statuses": "Statuses",
    "reports.invoices.draft": "Draft",
    "reports.invoices.sent": "Sent",
    "reports.invoices.paid": "Paid",
    "reports.invoices.overdue": "Overdue",
    "reports.invoices.filterByCompany": "Filter by company",
    "reports.invoices.allCompanies": "All Companies",
    "reports.invoices.filterByClient": "Filter by client",
    "reports.invoices.allClients": "All Clients",
    "reports.invoices.number": "Number",
    "reports.invoices.client": "Client",
    "reports.invoices.issueDate": "Issue Date",
    "reports.invoices.dueDate": "Due Date",
    "reports.invoices.amount": "Amount",
    "reports.invoices.status": "Status",
    "reports.invoices.noInvoicesFound": "No invoices found",
    "reports.invoices.download": "Download",
    "reports.invoices.exportDesc": "Export invoice report",
    "reports.overview.totalRevenue": "Total Revenue",
    "reports.overview.pendingInvoices": "Pending Invoices",
    "reports.overview.activeClients": "Active Clients",
    "reports.overview.activeProducts": "Active Products",
    "reports.overview.recentActivity": "Recent Activity",
    "reports.overview.recentActivityDesc": "Latest activities from your business",
    "reports.overview.noRecentActivity": "No recent activity",
    "reports.overview.loading": "Loading...",
    "reports.activity.invoiceSentTo": "Invoice {number} sent to {client}",
    "reports.activity.paymentReceived": "Payment received for {number}",
    "reports.activity.invoiceOverdue": "Invoice {number} is overdue",
    "reports.activity.newClientAdded": "New client added: {name}",
    "reports.activity.justNow": "Just now",
    "reports.activity.minutesAgo": "{count} minutes ago",
    "reports.activity.hoursAgo": "{count} hours ago",
    "reports.activity.daysAgo": "{count} days ago",
    "reports.activity.weeksAgo": "{count} weeks ago",
    "reports.revenue.customDateRange": "Custom Date Range",
    "reports.revenue.byMonth": "By Month",
    "reports.revenue.byYear": "By Year",
    "reports.revenue.title": "Revenue by Period",
    "reports.revenue.description": "Analyze revenue by custom date range, month, or year",
    "reports.revenue.noPeriodSelected": "No period selected",
    "reports.revenue.selectPeriod": "Please select a date range, month, or year to view revenue data.",
    "reports.revenue.startDate": "Start Date",
    "reports.revenue.endDate": "End Date",
    "reports.revenue.clear": "Clear",
    "reports.revenue.chooseMonth": "Choose a month",
    "reports.revenue.chooseYear": "Choose a year",
    "reports.revenue.monthLabel": "Month",
    "reports.revenue.yearLabel": "Year",
    "reports.revenue.paidInvoicesOnly": "Paid invoices only",
    "reports.revenue.numberOfMonths": "Number of months",
    "reports.revenue.numberOfYears": "Number of years",
    "reports.revenue.withRevenue": "With revenue",
    "reports.revenue.perMonth": "Per month",
    "reports.revenue.perYear": "Per year",
    "reports.expenses.title": "Expenses Report",
    "reports.expenses.description": "Expense analysis by company and category",
    "reports.expenses.byCategory": "Expenses by Category",
    "reports.expenses.byCategoryDesc": "Distribution of expense amounts by category",
    "reports.expenses.byCompany": "Expenses by Company",
    "reports.expenses.byCompanyDesc": "Distribution of expense amounts by client company",
    "reports.expenses.detailByCategory": "Detail by Category",
    "reports.expenses.detailByCategoryDesc": "Detailed breakdown of expenses by category",
    "reports.expenses.detailByCompany": "Detail by Company",
    "reports.expenses.detailByCompanyDesc": "Detailed breakdown of expenses by client company",
    "reports.expenses.category": "Category",
    "reports.expenses.count": "Count",
    "reports.expenses.totalAmount": "Total Amount",
    "reports.expenses.averageAmount": "Average Amount",
    "reports.expenses.company": "Company",
    "reports.products.profitTitle": "Product Profit Report",
    "reports.products.profitDesc": "Profitability analysis by sold product",
    "reports.products.inventoryTitle": "Inventory Report",
    "reports.products.inventoryDesc": "Stock analysis and inventory management",
    "reports.products.salesTitle": "Sales Report",
    "reports.products.salesDesc": "Sales analysis and performance by product",
    "reports.products.dateFilters": "Date Filters",
    "reports.products.selectPeriodProfit": "Select a period to analyze profits",
    "reports.products.selectPeriodSales": "Select a period to analyze sales",
    "reports.products.companyFilter": "Company Filter",
    "reports.products.companyFilterDesc": "Filter by company (optional)",
    "reports.products.filterType": "Filter Type",
    "reports.products.selectFilterType": "Select filter type",
    "reports.products.allCompanies": "All Companies",
    "reports.products.byCompany": "By Company",
    "reports.products.company": "Company",
    "reports.products.selectCompany": "Select company",
    "reports.products.loadingProfit": "Loading profit data...",
    "reports.products.loadingSales": "Loading sales data...",
    "reports.products.totalProfit": "Total Profit",
    "reports.products.totalRevenue": "Total Revenue",
    "reports.products.totalCost": "Total Cost",
    "reports.products.overallMargin": "Overall Margin",
    "reports.products.profitByProduct": "Profit by Product",
    "reports.products.profitByProductDesc": "Comparative analysis of profits generated by each product",
    "reports.products.productDetails": "Product Details",
    "reports.products.productDetailsDesc": "Detailed analysis of each product's profitability",
    "reports.products.product": "Product",
    "reports.products.qtySold": "Qty Sold",
    "reports.products.revenue": "Revenue",
    "reports.products.cost": "Cost",
    "reports.products.profit": "Profit",
    "reports.products.marginPercent": "Margin %",
    "reports.products.avgPrice": "Avg Price",
    "reports.products.noProfitData": "No profit data available for the selected period.",
    "reports.products.totalProducts": "Total Products",
    "reports.products.productsInInventory": "products in inventory",
    "reports.products.activeProducts": "Active Products",
    "reports.products.activeProductsCount": "active products",
    "reports.products.lowStockAlert": "Low Stock Alert",
    "reports.products.productsOutOfStock": "products out of stock",
    "reports.products.totalInventoryValue": "Total Inventory Value",
    "reports.products.totalInventoryValueDesc": "total inventory value",
    "reports.products.stockLevelsByProduct": "Stock Levels by Product",
    "reports.products.stockLevelsDesc": "Available quantities for each product",
    "reports.products.quantity": "Quantity",
    "reports.products.quantityLabel": "Quantity",
    "reports.products.noProductsFound": "No products found",
    "reports.products.inventoryDetails": "Product Details",
    "reports.products.inventoryDetailsDesc": "Complete information on all products",
    "reports.products.name": "Name",
    "reports.products.sku": "SKU",
    "reports.products.category": "Category",
    "reports.products.price": "Price",
    "reports.products.margin": "Margin",
    "reports.products.stockValue": "Stock Value",
    "reports.products.status": "Status",
    "reports.products.active": "Active",
    "reports.products.inactive": "Inactive",
    "reports.products.totalQuantitySold": "Total Quantity Sold",
    "reports.products.numberOfSales": "Number of Sales",
    "reports.products.productsSold": "Products Sold",
    "reports.products.servicesSold": "Services Sold",
    "reports.products.revenueByProduct": "Revenue by Product",
    "reports.products.revenueByProductDesc": "Sales performance analysis by physical products",
    "reports.products.revenueByService": "Revenue by Service",
    "reports.products.revenueByServiceDesc": "Sales performance analysis by services",
    "reports.products.salesDetails": "Sales Details",
    "reports.products.salesDetailsDesc": "Detailed sales information for products and services",
    "reports.products.productServiceLabel": "Product/Service",
    "reports.products.salesCount": "Sales Count",
    "reports.products.firstSale": "First Sale",
    "reports.products.lastSale": "Last Sale",
    "reports.products.productLabel": "Product",
    "reports.products.serviceLabel": "Service",
    "reports.products.noSalesData": "No sales data available for the selected period.",
    "reports.revenue.filterBy": "Filter by",
    "reports.revenue.all": "All",
    "reports.revenue.company": "Company",
    "reports.revenue.client": "Client",
    "reports.revenue.selectCompany": "Select company",
    "reports.revenue.selectClient": "Select client",
    "reports.revenue.monthlyRevenue": "Monthly Revenue",
    "reports.revenue.yearlyRevenue": "Yearly Revenue",
    "reports.revenue.option1": "Option 1: Select a specific year",
    "reports.revenue.option2": "Option 2: Select a year range",
    "reports.revenue.startYear": "Start Year",
    "reports.revenue.endYear": "End Year",
    "reports.revenue.viewMonthly": "View Monthly",
    "reports.revenue.viewYearly": "View Yearly",
    "reports.revenue.downloadPDF": "Download PDF",
    "reports.revenue.downloadExcel": "Download Excel",
    "reports.revenue.downloadCharts": "Download Charts",
    "reports.revenue.totalRevenue": "Total Revenue",
    "reports.revenue.numberOfInvoices": "Number of Invoices",
    "reports.revenue.averageRevenue": "Average Revenue",
    "reports.revenue.revenueEvolution": "Revenue Evolution by",
    "reports.revenue.revenueTrend": "Revenue Trend",
    "reports.revenue.detailsByPeriod": "Details by Period",
    "reports.revenue.detailedDataBy": "Detailed data by",
    "reports.revenue.period": "Period",
    "reports.revenue.revenue": "Revenue",
    "reports.revenue.invoices": "Invoices",
    "reports.revenue.averageRevenuePerInvoice": "Average Revenue per Invoice",
    "reports.revenue.invoicesList": "Invoices List",
    "reports.revenue.invoicesListDescription": "Detailed list of paid invoices in the selected period",
    "reports.revenue.invoiceNumber": "Invoice #",
    "reports.revenue.clientName": "Client",
    "reports.revenue.amount": "Amount",
    "reports.revenue.date": "Date",
    "reports.revenue.issueDate": "Issue Date",
    "reports.revenue.totalAmount": "Total Amount",
    "reports.revenue.status": "Status",
    "reports.revenue.month": "month",
    "reports.revenue.year": "year",
    "reports.revenue.monthly": "Monthly",
    "reports.revenue.yearly": "Yearly",
    "reports.products.profitMargin": "Profit Margin",
    "reports.products.productName": "Product",
    "reports.products.quantitySold": "Quantity Sold",
    "reports.products.profitDetails": "Product Profit Details",
    "reports.products.averageSalePrice": "Average Sale Price",
    "reports.products.averageCostPrice": "Average Cost Price",
    "reports.products.stockStatus": "Stock Status",
    "reports.products.currentStock": "Current Stock",
    "reports.products.unit": "Unit",
    "reports.products.lowStock": "Low stock",
    "reports.products.salesByProduct": "Sales by Product",
    "reports.products.salesByService": "Sales by Service",
    "reports.products.services": "Services",
    "reports.expenses.dateFilters": "Date Filters",
    "reports.expenses.filters": "Filters",
    "reports.expenses.filterBy": "Filter by",
    "reports.expenses.selectCategory": "Select category",
    "reports.expenses.totalExpenses": "Total Expenses",
    "reports.expenses.expensesByCategory": "Expenses by Category",
    "reports.expenses.expensesByCompany": "Expenses by Company",
    "reports.expenses.amount": "Amount",
    "reports.expenses.expenseDetails": "Expense Details",
    "reports.expenses.descriptionField": "Description",
    "reports.expenses.date": "Date",
    "reports.expenses.vendor": "Vendor",
    "reports.expenses.dateRange": "Date Range",
    "reports.expenses.filterType": "Filter Type",
    "reports.expenses.selectFilterType": "Select filter type",
    "reports.expenses.allExpenses": "All expenses",
    "reports.expenses.byCompanyFilter": "By company",
    "reports.expenses.byCategoryFilter": "By category",
    "reports.expenses.selectCompany": "Select a company",
    "reports.expenses.paidExpenses": "Paid Expenses",
    "reports.expenses.unpaidExpenses": "Unpaid Expenses",
    "reports.expenses.noData": "No expense data available",
    "reports.expenses.loading": "Loading expense data...",
    "reports.expenses.filtersCriteria": "Select criteria to filter expenses",
    "reports.expenses.allExpensesDetail": "All Expenses Detail",
    "reports.expenses.allExpensesDetailDesc": "Complete list of expenses with their taxes",
    "reports.expenses.taxes": "Taxes",
    "reports.expenses.total": "Total",
    "reports.expenses.status": "Status",
    "reports.expenses.paid": "Paid",
    "reports.expenses.unpaid": "Unpaid",
    "reports.expenses.noCategoryData": "No category data available",
    "reports.clients.title": "Clients Report",
    "reports.clients.description": "List of clients by company and statistics",
    "reports.clients.filters": "Filters",
    "reports.clients.filterDescription": "Filter clients by creation date",
    "reports.clients.createdFromDate": "Created from",
    "reports.clients.createdToDate": "Created to",
    "reports.clients.selectDate": "Select a date",
    "reports.clients.clearFilters": "Clear filters",
    "reports.clients.allClients": "All Clients",
    "reports.clients.allClientsDescription": "Complete list of all clients",
    "reports.clients.clientName": "Client Name",
    "reports.clients.company": "Company",
    "reports.clients.contactPerson": "Contact Person",
    "reports.clients.creationDate": "Creation Date",
    "reports.clients.noCompany": "No company",
    "reports.clients.noClientsFound": "No clients found for this period",
    "reports.clients.clientsByCompany": "Clients by Company",
    "reports.clients.clientsByCompanyDesc": "Distribution of clients by their companies",
    "reports.clients.clientCount": "client",
    "reports.clients.clientCountPlural": "clients",
    "reports.clients.noClientsForCompany": "No clients associated with this company",
    "reports.clients.clientsWithoutCompany": "Clients without assigned company",
    "reports.clients.dateFilters": "Date Filters",
    "reports.clients.createdFrom": "Created From",
    "reports.clients.createdTo": "Created To",
    "reports.clients.totalClients": "Total Clients",
    "reports.clients.clientsList": "Clients List",
    "reports.clients.name": "Name",
    "reports.clients.email": "Email",
    "reports.clients.phone": "Phone",
    "reports.clients.totalInvoiced": "Total Invoiced",
    "reports.clients.lastInvoice": "Last Invoice",
    "reports.clients.createdOn": "Created On",
    "reports.clients.noInvoice": "No invoice",
    "reports.taxes.dateRange": "Date Range",
    "reports.taxes.selectMonth": "Select Month",
    "reports.taxes.selectYear": "Select Year",
    "reports.taxes.companyFilter": "Company Filter",
    "reports.taxes.allCompanies": "All Companies",
    "reports.taxes.taxSummary": "Tax Summary",
    "reports.taxes.totalTaxCollected": "Total Tax Collected",
    "reports.taxes.totalRevenue": "Total Revenue",
    "reports.taxes.taxesByRate": "Taxes by Rate",
    "reports.taxes.taxRate": "Tax Rate",
    "reports.taxes.taxAmount": "Tax Amount",
    "reports.taxes.taxDetails": "Tax Details by Period",
    "reports.taxes.invoicesWithTax": "Invoices with Tax",
    "reports.taxes.filters": "Tax Report Filters",
    "reports.taxes.company": "Company",
    "reports.taxes.periodType": "Period Type",
    "reports.taxes.customDates": "Custom dates",
    "reports.taxes.byMonth": "By month",
    "reports.taxes.byYear": "By year",
    "reports.taxes.display": "Display",
    "reports.taxes.monthly": "Monthly",
    "reports.taxes.yearly": "Yearly",
    "reports.taxes.startDate": "Start date",
    "reports.taxes.endDate": "End date",
    "reports.taxes.select": "Select",
    "reports.taxes.month": "Month",
    "reports.taxes.year": "Year",
    "reports.taxes.grandTotal": "Grand Total of Taxes",
    "reports.taxes.totalByType": "Total by Tax Type",
    "reports.taxes.invoice": "invoice",
    "reports.taxes.invoices": "invoices",
    "reports.taxes.distribution": "Tax Distribution",
    "reports.taxes.amount": "Amount",
    "reports.taxes.taxesAmount": "Tax amount",
    "reports.taxes.evolutionBy": "Tax Evolution by",
    "reports.taxes.noData": "No tax data",
    "reports.taxes.noDataDesc": "No paid invoices with taxes found for this period.",
    "reports.taxes.summaryCollected": "Summary of Collected Taxes",
    "reports.taxes.summaryDesc": "Overview of taxes by type",
    "reports.taxes.taxType": "Tax Type",
    "reports.taxes.totalAmount": "Total Amount",
    "reports.taxes.invoiceCount": "Number of Invoices",
    "reports.taxes.detailBy": "Tax Details by",
    "reports.taxes.period": "Period",
    "reports.taxes.totalTaxes": "Total Taxes",
    "reports.taxes.invoicesLabel": "Invoices",
    "reports.taxes.detailByTax": "Detail by Tax",
    "reports.taxes.download": "Download",
    "reports.taxes.exportDesc": "Export tax report",
    
    // PDF Reports
    "reports.pdf.allPeriods": "All Periods",
    "reports.pdf.since": "Since",
    "reports.pdf.until": "Until",
    "reports.pdf.period": "Period",
    "reports.pdf.allCompanies": "All Companies",
    "reports.pdf.company": "Company",
    "reports.pdf.reportDate": "Report date",
    "reports.pdf.totalProducts": "Total products",
    "reports.pdf.activeProducts": "Active products",
    "reports.pdf.lowStockAlerts": "Low stock alerts",
    "reports.pdf.totalInventoryValue": "Total inventory value",
    "reports.pdf.summary": "Summary",
    "reports.pdf.salesReport": "Sales Report",
    "reports.pdf.productProfitReport": "Product Profit Report",
    "reports.pdf.inventoryReport": "Inventory Report",
    "reports.pdf.expenseReport": "Expense Report",
    "reports.pdf.clientReport": "Client Report",
    "reports.pdf.revenueByProductChart": "Revenue by Product Chart",
    "reports.pdf.revenueByServiceChart": "Revenue by Service Chart",
    "reports.pdf.salesDetails": "Sales Details",
    "reports.pdf.profitByProductChart": "Profit by Product Chart",
    "reports.pdf.productDetails": "Product Details",
    
    
    // Settings
    "settings.title": "Settings",
    "settings.description": "Manage your account settings",
    "settings.account.title": "Account Information",
    "settings.account.description": "Your personal information",
    "settings.account.email": "Email",
    "settings.account.username": "Username",
    "settings.account.usernamePlaceholder": "Enter your username",
    "settings.account.usernameDescription": "Your unique username for the account",
    "settings.account.save": "Save",
    "settings.account.saving": "Saving...",
    "settings.account.usernameUpdated": "Username updated",
    "settings.account.usernameUpdatedDescription": "Your username has been successfully updated",
    "settings.account.usernameError": "Error updating username",
    "settings.appearance.title": "Appearance",
    "settings.appearance.description": "Customize the application appearance according to your preferences",
    "settings.appearance.displayMode": "Display Mode",
    "settings.appearance.light": "Light",
    "settings.appearance.dark": "Dark",
    "settings.appearance.colorTheme": "Color Theme",
    "settings.appearance.classic": "Classic (Blue)",
    "settings.appearance.modern": "Modern (Purple)",
    "settings.appearance.warm": "Warm (Orange)",
    "settings.appearance.nature": "Nature (Green)",
    "settings.language.title": "Language",
    "settings.language.description": "Choose your preferred language",
    "settings.language.english": "English",
    "settings.language.french": "Français",
    "settings.invoice.title": "Invoice Design",
    "settings.invoice.description": "Choose your preferred invoice template",
    "settings.invoice.templateLabel": "Invoice Template",
    "settings.invoice.classic": "Classic",
    "settings.invoice.modern": "Modern",
    "settings.invoice.professional": "Professional",
    "settings.invoice.creative": "Creative",
    "settings.invoice.colorLabel": "Invoice Color",
    "settings.invoice.blue": "Blue",
    "settings.invoice.green": "Green",
    "settings.invoice.purple": "Purple",
    "settings.invoice.orange": "Orange",
    "settings.invoice.yellow": "Yellow",
    "settings.invoice.gray": "Gray",
    "settings.invoice.preview": "Preview",
    
    // Password Change
    "password.title": "Change Password",
    "password.description": "Update your password to secure your account",
    "password.new": "New Password",
    "password.confirm": "Confirm New Password",
    "password.button": "Change Password",
    "password.updating": "Updating...",
    "password.error.length": "New password must be at least 6 characters",
    "password.error.match": "Passwords do not match",
    "password.success.title": "Success",
    "password.success.description": "Your password has been successfully updated.",
    "password.error.title": "Error",
    
    // Auth
    "auth.title": "Business Management",
    "auth.subtitle": "Sign in to your account or create a new one",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signingIn": "Signing in...",
    "auth.displayName": "Display Name",
    "auth.creatingAccount": "Creating account...",
    "auth.createAccount": "Create Account",
    "auth.forgotPassword": "Forgot your password?",
    "auth.signInFailed": "Sign in failed",
    "auth.welcomeBack": "Welcome back!",
    "auth.signInSuccess": "You have successfully signed in.",
    "auth.signUpFailed": "Sign up failed",
    "auth.accountCreated": "Account created!",
    "auth.checkEmail": "Please check your email to verify your account.",
    "auth.displayNameRequired": "Display name is required",
    "auth.resetPassword": "Reset Password",
    "auth.resetPasswordDesc": "Enter your email address and we'll send you a link to reset your password.",
    "auth.resetFailed": "Reset failed",
    "auth.resetEmailSent": "Reset email sent!",
    "auth.checkResetEmail": "Please check your email for reset instructions.",
    "auth.sending": "Sending...",
    "auth.sendResetLink": "Send Reset Link",
    "auth.updatePassword": "Update Password",
    "auth.updatePasswordDesc": "Enter your new password below.",
    "auth.newPassword": "New Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.updating": "Updating...",
    "auth.updateFailed": "Update failed",
    "auth.passwordUpdated": "Password updated!",
    "auth.passwordUpdateSuccess": "Your password has been successfully updated.",
    "auth.passwordsDoNotMatch": "Passwords do not match",
    "auth.passwordTooShort": "Password must be at least 6 characters long",
    "auth.cancel": "Cancel",
    
    // PWA Install Banner
    "pwa.install.title": "Install GestionFlow",
    "pwa.install.description": "Add to your desktop for quick access and offline use.",
    "pwa.install.button": "Install",
    "pwa.install.later": "Not now",
  },
  fr: {
    reports: "Rapports",
    reportsDescription: "Analyses commerciales et indicateurs de performance",
    // App Title
    "app.title": "Système de Gestion d'Entreprise",
    
    // Sidebar Navigation
    "nav.title": "Gestion d'Entreprise",
    "nav.main": "Principal",
    "nav.system": "Système",
    "nav.dashboard": "Tableau de bord",
    "nav.companies": "Entreprises",
    "nav.clients": "Clients",
    "nav.categories": "Catégories",
    "nav.products": "Produits & Services",
    "nav.stockManagement": "Gestion des stocks",
    "nav.quotes": "Devis",
    "nav.invoices": "Factures",
    "nav.timeTracking": "Suivi des heures",
    "nav.expenses": "Dépenses",
    "nav.reports": "Rapports",
    "nav.pricing": "Tarification",
    "nav.settings": "Paramètres",
    "nav.admin": "Admin",
    
    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.subtitle": "Aperçu des performances de votre entreprise",
    "dashboard.totalRevenue": "Revenu total",
    "dashboard.totalRevenue.desc": "Provenant des factures payées",
    "dashboard.activeClients": "Clients actifs",
    "dashboard.newThisMonth": "nouveaux ce mois-ci",
    "dashboard.openInvoices": "Factures ouvertes",
    "dashboard.total": "Total",
    "dashboard.productsServices": "Produits/Services",
    "dashboard.activeProducts": "Produits actifs",
    "dashboard.loading": "Chargement...",
    "dashboard.recentActivity": "Activité récente",
    "dashboard.recentActivity.desc": "Dernières transactions et mises à jour",
    "dashboard.noActivity": "Aucune activité récente",
    "dashboard.quickActions": "Actions rapides",
    "dashboard.quickActions.desc": "Tâches courantes et raccourcis",
    "dashboard.createInvoice": "Créer une nouvelle facture",
    "dashboard.addClient": "Ajouter un nouveau client",
    "dashboard.addProduct": "Ajouter un produit/service",
    "dashboard.viewReports": "Voir les rapports",
    
    // Companies
    "companies.title": "Entreprises",
    "companies.subtitle": "Gérez vos entreprises et organisations",
    "companies.addButton": "Ajouter une entreprise",
    "companies.loading": "Chargement...",
    "companies.dialog.add": "Ajouter une nouvelle entreprise",
    "companies.dialog.edit": "Modifier l'entreprise",
    "companies.dialog.addDesc": "Ajoutez une nouvelle entreprise à votre système de gestion.",
    "companies.dialog.editDesc": "Mettre à jour les informations de l'entreprise.",
    "companies.name": "Nom de l'entreprise",
    "companies.namePlaceholder": "Entrez le nom de l'entreprise",
    "companies.address": "Adresse",
    "companies.streetAddress": "Adresse de rue",
    "companies.streetPlaceholder": "123 rue Principale",
    "companies.city": "Ville",
    "companies.cityPlaceholder": "Nom de la ville",
    "companies.provinceState": "Province/État",
    "companies.provinceStatePlaceholder": "Sélectionnez la province/état",
    "companies.postalCode": "Code postal",
    "companies.postalPlaceholder": "A1A 1A1",
    "companies.country": "Pays",
    "companies.countryPlaceholder": "Sélectionnez le pays",
    "companies.phone": "Téléphone",
    "companies.phonePlaceholder": "Entrez le numéro de téléphone",
    "companies.email": "Email",
    "companies.emailPlaceholder": "entreprise@exemple.com",
    "companies.website": "Site web",
    "companies.websitePlaceholder": "www.exemple.com",
    "companies.taxId": "Numéro fiscal",
    "companies.taxIdPlaceholder": "Entrez le numéro fiscal",
    "companies.contactPerson": "Personne-contact",
    "companies.contactPlaceholder": "Entrez le nom de la personne-contact",
    "companies.logo": "Logo de l'entreprise",
    "companies.uploadLogo": "Télécharger le logo",
    "companies.currentLogo": "Logo actuel",
    "companies.taxes": "Taxes",
    "companies.taxName": "Nom de la taxe",
    "companies.taxNamePlaceholder": "ex: TPS, TVQ",
    "companies.taxRate": "Taux de taxe (%)",
    "companies.taxRatePlaceholder": "0.00",
    "companies.addTax": "Ajouter une taxe",
    "companies.invoiceSettings": "Paramètres de facturation",
    "companies.dueDefault": "Jours d'échéance par défaut",
    "companies.invoicePrefix": "Préfixe de numéro de facture",
    "companies.invoicePrefixPlaceholder": "FACT",
    "companies.invoiceDigits": "Nombre de chiffres de facture",
    "companies.invoiceStart": "Numéro de facture de départ",
    "companies.emailTemplates": "Modèles d'email",
    "companies.invoiceEmailSubject": "Sujet de l'email de facture",
    "companies.invoiceEmailMessage": "Message de l'email de facture",
    "companies.overdueSubject": "Sujet de l'email de retard",
    "companies.overdueMessage": "Message de l'email de retard",
    "companies.paymentSubject": "Sujet de confirmation de paiement",
    "companies.paymentMessage": "Message de confirmation de paiement",
    "companies.invoiceFooter": "Message de bas de page de facture",
    "companies.invoiceFooterDesc": "Message affiché au bas de toutes les factures",
    "companies.cancel": "Annuler",
    "companies.updateButton": "Mettre à jour l'entreprise",
    "companies.addCompany": "Ajouter l'entreprise",
    "companies.uploadingLogo": "Téléchargement du logo...",
    "companies.logoError": "Échec du téléchargement du logo. Veuillez réessayer.",
    "companies.logoHint": "PNG, JPG, GIF ou WEBP (max 2 Mo)",
    "companies.validation.error": "Erreur de validation",
    "companies.validation.logoFormatError": "Format de logo invalide. Veuillez utiliser PNG, JPG, GIF ou WEBP.",
    "companies.validation.logoSizeError": "Le fichier logo est trop volumineux. La taille maximale est de 2 Mo.",
    "companies.validation.prefixConflict": "Une autre compagnie utilise déjà ce préfixe de facture. Veuillez choisir un préfixe différent pour éviter les conflits de numéros de facture.",
    "companies.validation.numberConflict": "La configuration de numérotation des factures créerait des conflits avec les factures existantes : {numbers}. Veuillez ajuster le préfixe, le numéro de départ ou les chiffres.",
    "companies.validation.nameRequired": "Le nom de l'entreprise est obligatoire",
    "companies.validation.emailRequired": "L'email est obligatoire",
    "companies.validation.emailInvalid": "Veuillez entrer une adresse email valide",
    "companies.validation.phoneInvalid": "Veuillez entrer un numéro de téléphone valide (ex: +1 234 567-8900)",
    "companies.validation.invoicePrefixRequired": "Le préfixe de facture est obligatoire",
    "companies.validation.invoiceDigitsRequired": "Le nombre de chiffres doit être au moins 1",
    "companies.validation.invoiceStartNumberRequired": "Le numéro de départ doit être au moins 1",
    "companies.delete": "Supprimer l'entreprise",
    "companies.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cette entreprise ? Cette action ne peut pas être annulée.",
    "companies.deleteButton": "Supprimer",
    "companies.companyLabel": "Entreprise",
    "companies.websiteLabel": "Site web",
    "companies.taxIdLabel": "Numéro fiscal",
    "companies.taxesLabel": "Taxes",
    
    // Clients
    "clients.title": "Clients",
    "clients.subtitle": "Gérez vos clients et relations avec la clientèle",
    "clients.addButton": "Ajouter un client",
    "clients.dialog.add": "Ajouter un nouveau client",
    "clients.dialog.edit": "Modifier le client",
    "clients.dialog.addDesc": "Ajoutez un nouveau client à votre base de données clients.",
    "clients.dialog.editDesc": "Mettre à jour les informations du client.",
    "clients.name": "Nom du client",
    "clients.namePlaceholder": "Entrez le nom du client",
    "clients.contactPerson": "Personne-contact",
    "clients.contactPlaceholder": "Entrez le nom de la personne-contact",
    "clients.serviceProvider": "Compagnie",
    "clients.serviceProviderPlaceholder": "Sélectionnez la compagnie",
    "clients.emails": "Email(s)",
    "clients.emailPlaceholder": "Entrez l'adresse email",
    "clients.addEmail": "Ajouter un autre email",
    "clients.phone": "Téléphone",
    "clients.phonePlaceholder": "Entrez le numéro de téléphone",
    "clients.address": "Adresse",
    "clients.addressPlaceholder": "Entrez l'adresse",
    "clients.language": "Langue",
    "clients.languagePlaceholder": "Sélectionnez la langue",
    "clients.english": "English",
    "clients.french": "Français",
    "clients.hourlyRate": "Taux horaire ($)",
    "clients.hourlyRatePlaceholder": "Entrez le taux horaire",
    "clients.notes": "Notes",
    "clients.notesPlaceholder": "Entrez des notes sur ce client",
    "clients.creationDate": "Date de création",
    "clients.cancel": "Annuler",
    "clients.updateButton": "Mettre à jour le client",
    "clients.addClient": "Ajouter le client",
    "clients.searchPlaceholder": "Rechercher des clients...",
    "clients.listTitle": "Liste des clients",
    "clients.listDesc": "Une liste complète de tous vos clients",
    "clients.tableClientName": "Nom du client",
    "clients.tableContactPerson": "Personne-contact",
    "clients.tableServiceProvider": "Compagnie",
    "clients.tableContactInfo": "Coordonnées",
    "clients.tableAddress": "Adresse",
    "clients.tableLanguage": "Langue",
    "clients.tableHourlyRate": "Taux horaire",
    "clients.tableCreated": "Créé",
    "clients.tableActions": "Actions",
    "clients.delete": "Supprimer le client",
    "clients.deleteConfirm": "Êtes-vous sûr de vouloir supprimer {name} ? Cette action ne peut pas être annulée.",
    "clients.deleteButton": "Supprimer",
    "clients.validation.error": "Erreur de validation",
    "clients.validation.companyRequired": "Veuillez sélectionner une entreprise",
    "clients.validation.emailRequired": "Au moins un email est requis",
    "clients.validation.emailInvalid": "Veuillez entrer une adresse email valide",
    "clients.validation.phoneInvalid": "Veuillez entrer un numéro de téléphone valide (ex: +1 234 567-8900)",
    "clients.hourlyPlaceholder": "Entrez le taux horaire",
    
    // Products
    "products.title": "Produits & Services",
    "products.subtitle": "Gérez votre catalogue de produits et services",
    "products.addButton": "Ajouter un article",
    "products.dialog.add": "Ajouter un nouvel article",
    "products.dialog.edit": "Modifier l'article",
    "products.dialog.addDesc": "Ajoutez un nouveau produit ou service à votre catalogue.",
    "products.dialog.editDesc": "Mettre à jour les informations du produit ou service.",
    "products.type": "Type",
    "products.typePlaceholder": "Sélectionnez le type",
    "products.product": "Produit",
    "products.service": "Service",
    "products.name": "Nom",
    "products.namePlaceholder": "Entrez le nom de l'article",
    "products.description": "Description",
    "products.descPlaceholder": "Entrez la description de l'article",
    "products.costPrice": "Prix coûtant",
    "products.salePrice": "Prix de vente",
    "products.category": "Catégorie",
    "products.categoryPlaceholder": "Sélectionnez la catégorie",
    "products.quantity": "Quantité",
    "products.quantityPlaceholder": "Entrez la quantité",
    "products.unit": "Unité",
    "products.unitPlaceholder": "Sélectionnez l'unité",
    "products.cancel": "Annuler",
    "products.updateButton": "Mettre à jour l'article",
    "products.addItem": "Ajouter l'article",
    "products.searchPlaceholder": "Rechercher des produits et services...",
    "products.allItems": "Tous les articles",
    "products.products": "Produits",
    "products.services": "Services",
    "products.active": "Actif",
    "products.inactive": "Inactif",
    "products.salePrice2": "Prix de vente",
    "products.cost": "Coût",
    "products.stock": "Stock",
    "products.delete": "Supprimer",
    "products.deleteConfirm": "Êtes-vous sûr de vouloir supprimer \"{name}\" ? Cette action ne peut pas être annulée.",
    "products.deleteButton": "Supprimer",
    "products.catWebDev": "Développement Web",
    "products.catMobileDev": "Développement Mobile",
    "products.catSoftware": "Logiciel",
    "products.catConsulting": "Consultation",
    "products.catHardware": "Matériel",
    "products.catDesign": "Design",
    "products.catMarketing": "Marketing",
    "products.catTraining": "Formation",
    "products.catSupport": "Support",
    "products.catMaintenance": "Maintenance",
    "products.catHosting": "Hébergement",
    "products.catCloudServices": "Services Cloud",
    "products.catSecurity": "Sécurité",
    "products.catDataAnalysis": "Analyse de données",
    "products.catContentCreation": "Création de contenu",
    "products.catPhotography": "Photographie",
    "products.catVideoProduction": "Production vidéo",
    "products.catTranslation": "Traduction",
    "products.catLegalServices": "Services juridiques",
    "products.catAccounting": "Comptabilité",
    "products.catOther": "Autre",
    "products.unitPiece": "Pièce",
    "products.unitHour": "Heure",
    "products.unitDay": "Jour",
    "products.unitMonth": "Mois",
    "products.unitYear": "Année",
    
    // Invoices
    "invoices.title": "Factures",
    "invoices.subtitle": "Créer et gérer vos factures",
    "invoices.createButton": "Créer une facture",
    "invoices.dialog.edit": "Modifier la facture",
    "invoices.dialog.create": "Créer une nouvelle facture",
    "invoices.dialog.editDesc": "Mettre à jour les informations de la facture.",
    "invoices.dialog.createDesc": "Créer une nouvelle facture avec plusieurs produits ou services.",
    "invoices.selectCompany": "Sélectionner l'entreprise",
    "invoices.companyPlaceholder": "Sélectionner l'entreprise",
    "invoices.selectClient": "Sélectionner le client",
    "invoices.clientPlaceholder": "Sélectionner le client",
    "invoices.clientPlaceholderNoCompany": "Sélectionner d'abord l'entreprise",
    "invoices.issueDate": "Date de facture",
    "invoices.dueDate": "Date d'échéance",
    "invoices.terms": "Conditions",
    "invoices.termsPlaceholder": "Conditions de paiement",
    "invoices.notes": "Notes",
    "invoices.notesPlaceholder": "Notes supplémentaires",
    "invoices.addItems": "Ajouter des articles",
    "invoices.selectProduct": "Sélectionner un produit/service (optionnel)",
    "invoices.productPlaceholder": "Sélectionner un produit/service existant ou entrer personnalisé",
    "invoices.customItem": "Article personnalisé",
    "invoices.addNewProduct": "Ajouter un nouveau produit/service",
    "invoices.description": "Description",
    "invoices.descPlaceholder": "Description de l'article",
    "invoices.quantity": "Quantité",
    "invoices.unitPrice": "Prix unitaire",
    "invoices.itemNotes": "Notes (optionnel)",
    "invoices.itemNotesPlaceholder": "Notes de l'article",
    "invoices.addItemButton": "Ajouter l'article",
    "invoices.updateItem": "Mettre à jour l'article",
    "invoices.invoiceItems": "Articles de la facture",
    "invoices.total": "Total",
    "invoices.remove": "Retirer",
    "invoices.subtotal": "Sous-total",
    "invoices.taxAmount": "Montant des taxes",
    "invoices.totalAmount": "Montant total",
    "invoices.cancel": "Annuler",
    "invoices.saveInvoice": "Enregistrer la facture",
    "invoices.updateInvoice": "Mettre à jour la facture",
    "invoices.loading": "Chargement...",
    "invoices.filterByStatus": "Filtrer par statut",
    "invoices.statusAll": "Tous les statuts",
    "invoices.statusDraft": "Brouillon",
    "invoices.statusSent": "Envoyée",
    "invoices.statusPaid": "Payée",
    "invoices.statusOverdue": "En retard",
    "invoices.filterByClient": "Filtrer par client",
    "invoices.clientAll": "Tous les clients",
    "invoices.filterByCompany": "Filtrer par entreprise",
    "invoices.companyAll": "Toutes les entreprises",
    "invoices.archiveButton": "Archiver",
    "invoices.unarchiveButton": "Désarchiver",
    "invoices.archived": "Archivée",
    "invoices.showArchived": "Factures archivées",
    "invoices.showActive": "Factures actives",
    "invoices.listTitle": "Liste des factures",
    "invoices.listDesc": "Gérez toutes vos factures en un seul endroit",
    "invoices.tableInvoiceNumber": "Facture #",
    "invoices.tableClient": "Client",
    "invoices.tableAmount": "Montant",
    "invoices.tableStatus": "Statut",
    "invoices.tableIssueDate": "Date d'émission",
    "invoices.tableDueDate": "Date d'échéance",
    "invoices.tableItems": "Articles",
    "invoices.tableActions": "Actions",
    "invoices.delete": "Supprimer la facture",
    "invoices.deleteConfirm": "Êtes-vous sûr de vouloir supprimer la facture {number} ? Cette action ne peut pas être annulée.",
    "invoices.deleteButton": "Supprimer",
    "invoices.emailDialog.title": "Envoyer la facture par email",
    "invoices.emailDialog.desc": "Choisir le type d'email et personnaliser le message avant l'envoi",
    "invoices.emailType": "Type d'email",
    "invoices.emailTypeNew": "Nouvelle facture",
    "invoices.emailTypeOverdue": "Rappel de paiement en retard",
    "invoices.emailTypeConfirmation": "Confirmation de paiement",
    "invoices.emailClient": "Client :",
    "invoices.emailInvoice": "Facture :",
    "invoices.emailRecipients": "Sélectionner les destinataires",
    "invoices.emailNoEmails": "Aucune adresse email trouvée pour ce client",
    "invoices.emailCC": "CC (Optionnel)",
    "invoices.emailCCPlaceholder": "Entrer une adresse email en CC",
    "invoices.emailAddCC": "Ajouter un email en CC",
    "invoices.emailSubject": "Sujet de l'email",
    "invoices.emailSubjectPlaceholder": "Sujet de l'email",
    "invoices.emailMessage": "Message de l'email",
    "invoices.emailMessagePlaceholder": "Message de l'email",
    "invoices.emailPlaceholders": "Espaces réservés disponibles : {client_name}, {invoice_number}, {issue_date}, {due_date}, {total}, {company_name}, {days_overdue}",
    "invoices.sendEmail": "Envoyer l'email",
    "invoices.sending": "Envoi en cours...",
    "invoices.totalInvoices": "Total des factures",
    "invoices.totalAmountLabel": "Montant total",
    "invoices.paidAmount": "Montant payé",
    "invoices.outstanding": "En suspens",
    "invoices.searchPlaceholder": "Rechercher des factures...",
    "invoices.filterBy": "Filtrer par",
    "invoices.allInvoices": "Toutes les factures",
    "invoices.byClient": "Par client",
    "invoices.byCompany": "Par entreprise",
    
    // Expenses
    "expenses.title": "Dépenses",
    "expenses.subtitle": "Suivez et gérez vos dépenses d'entreprise",
    "expenses.addButton": "Ajouter une dépense",
    "expenses.dialog.add": "Ajouter une nouvelle dépense",
    "expenses.dialog.edit": "Modifier la dépense",
    "expenses.dialog.addDesc": "Enregistrez une nouvelle dépense d'entreprise.",
    "expenses.dialog.editDesc": "Mettre à jour les informations de la dépense.",
    "expenses.description": "Description",
    "expenses.descPlaceholder": "Entrez la description de la dépense",
    "expenses.amount": "Montant",
    "expenses.amountPlaceholder": "0.00",
    "expenses.category": "Catégorie",
    "expenses.categoryPlaceholder": "Sélectionnez la catégorie",
    "expenses.date": "Date",
    "expenses.company": "Compagnie",
    "expenses.companyPlaceholder": "Sélectionnez la compagnie (optionnel)",
    "expenses.vendor": "Fournisseur",
    "expenses.vendorPlaceholder": "Entrez le nom du fournisseur",
    "expenses.status": "Statut",
    "expenses.statusPlaceholder": "Sélectionnez le statut",
    "expenses.notes": "Notes",
    "expenses.notesPlaceholder": "Notes supplémentaires...",
    "expenses.cancel": "Annuler",
    "expenses.updateButton": "Mettre à jour la dépense",
    "expenses.addExpense": "Ajouter la dépense",
    "expenses.total": "Total des dépenses",
    "expenses.paid": "Payé",
    "expenses.unpaid": "Non payé",
    "expenses.listTitle": "Liste des dépenses",
    "expenses.listDesc": "Toutes vos dépenses d'entreprise",
    "expenses.tableDescription": "Description",
    "expenses.tableAmount": "Montant",
    "expenses.tableCategory": "Catégorie",
    "expenses.tableDate": "Date",
    "expenses.tableClient": "Client",
    "expenses.tableVendor": "Fournisseur",
    "expenses.tableStatus": "Statut",
    "expenses.tableActions": "Actions",
    "expenses.delete": "Supprimer la dépense",
    "expenses.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cette dépense ? Cette action ne peut pas être annulée.",
    "expenses.loading": "Chargement...",
    "expenses.categories.Office": "Bureau",
    "expenses.categories.Meals": "Repas",
    "expenses.categories.Travel": "Voyage",
    "expenses.categories.Software": "Logiciel",
    "expenses.categories.Marketing": "Marketing",
    "expenses.categories.Utilities": "Services publics",
    "expenses.categories.Products": "Produits",
    "expenses.categories.Other": "Autre",
    
    // Reports
    "reports.title": "Rapports",
    "reports.subtitle": "Rapports financiers et analyses",
    "reports.tabs.overview": "Aperçu",
    "reports.tabs.revenue": "Revenus",
    "reports.tabs.products": "Stock",
    "reports.tabs.expenses": "Dépenses",
    "reports.tabs.clients": "Clients",
    "reports.tabs.taxes": "Taxes",
    "reports.tabs.invoices": "Factures",
    "reports.invoices.listTitle": "Liste des factures",
    "reports.invoices.listDesc": "{count} facture(s) trouvée(s)",
    "reports.invoices.grandTotal": "Grand Total",
    "reports.invoices.filterByStatus": "Filtrer par statut ({count})",
    "reports.invoices.allStatuses": "Tous",
    "reports.invoices.statuses": "Statuts",
    "reports.invoices.draft": "Brouillon",
    "reports.invoices.sent": "Envoyé",
    "reports.invoices.paid": "Payé",
    "reports.invoices.overdue": "En retard",
    "reports.invoices.filterByCompany": "Filtrer par compagnie",
    "reports.invoices.allCompanies": "Toutes les compagnies",
    "reports.invoices.filterByClient": "Filtrer par client",
    "reports.invoices.allClients": "Tous les clients",
    "reports.invoices.number": "Numéro",
    "reports.invoices.client": "Client",
    "reports.invoices.issueDate": "Date d'émission",
    "reports.invoices.dueDate": "Date d'échéance",
    "reports.invoices.amount": "Montant",
    "reports.invoices.status": "Statut",
    "reports.invoices.noInvoicesFound": "Aucune facture trouvée",
    "reports.invoices.download": "Téléchargement",
    "reports.invoices.exportDesc": "Exporter le rapport des factures",
    "reports.overview.totalRevenue": "Revenus totaux",
    "reports.overview.pendingInvoices": "Factures en attente",
    "reports.overview.activeClients": "Clients actifs",
    "reports.overview.activeProducts": "Produits actifs",
    "reports.overview.recentActivity": "Activité récente",
    "reports.overview.recentActivityDesc": "Les dernières activités de votre entreprise",
    "reports.overview.noRecentActivity": "Aucune activité récente",
    "reports.overview.loading": "Chargement...",
    "reports.activity.invoiceSentTo": "Facture {number} envoyée à {client}",
    "reports.activity.paymentReceived": "Paiement reçu pour {number}",
    "reports.activity.invoiceOverdue": "Facture {number} en retard",
    "reports.activity.newClientAdded": "Nouveau client ajouté : {name}",
    "reports.activity.justNow": "À l'instant",
    "reports.activity.minutesAgo": "Il y a {count} minutes",
    "reports.activity.hoursAgo": "Il y a {count} heures",
    "reports.activity.daysAgo": "Il y a {count} jours",
    "reports.activity.weeksAgo": "Il y a {count} semaines",
    "reports.revenue.customDateRange": "Plage de dates personnalisée",
    "reports.revenue.byMonth": "Par mois",
    "reports.revenue.byYear": "Par année",
    "reports.revenue.title": "Revenus par période",
    "reports.revenue.description": "Analysez les revenus par plage de dates personnalisée, par mois ou par année",
    "reports.revenue.noPeriodSelected": "Aucune période sélectionnée",
    "reports.revenue.selectPeriod": "Veuillez sélectionner une plage de dates, un mois ou une année pour voir les données de revenus.",
    "reports.revenue.startDate": "Date de début",
    "reports.revenue.endDate": "Date de fin",
    "reports.revenue.clear": "Effacer",
    "reports.revenue.chooseMonth": "Choisir un mois",
    "reports.revenue.chooseYear": "Choisir une année",
    "reports.revenue.monthLabel": "Mois",
    "reports.revenue.yearLabel": "Année",
    "reports.revenue.paidInvoicesOnly": "Factures payées uniquement",
    "reports.revenue.numberOfMonths": "Nombre de mois",
    "reports.revenue.numberOfYears": "Nombre d'années",
    "reports.revenue.withRevenue": "Avec revenu",
    "reports.revenue.perMonth": "Par mois",
    "reports.revenue.perYear": "Par année",
    "reports.expenses.title": "Rapport des dépenses",
    "reports.expenses.description": "Analyse des dépenses par compagnie et catégorie",
    "reports.expenses.byCategory": "Dépenses par catégorie",
    "reports.expenses.byCategoryDesc": "Répartition des montants de dépenses par catégorie",
    "reports.expenses.byCompany": "Dépenses par entreprise",
    "reports.expenses.byCompanyDesc": "Répartition des montants de dépenses par entreprise",
    "reports.expenses.detailByCategory": "Détails par catégorie",
    "reports.expenses.detailByCategoryDesc": "Ventilation détaillée des dépenses par catégorie",
    "reports.expenses.detailByCompany": "Détails par entreprise",
    "reports.expenses.detailByCompanyDesc": "Ventilation détaillée des dépenses par entreprise",
    "reports.expenses.category": "Catégorie",
    "reports.expenses.count": "Nombre",
    "reports.expenses.totalAmount": "Montant total",
    "reports.expenses.averageAmount": "Montant moyen",
    "reports.expenses.company": "Entreprise",
    "reports.products.profitTitle": "Rapport des profits par produit",
    "reports.products.profitDesc": "Analyse de rentabilité par produit vendu",
    "reports.products.inventoryTitle": "Rapport d'inventaire",
    "reports.products.inventoryDesc": "Analyse des stocks et gestion de l'inventaire",
    "reports.products.salesTitle": "Rapport des ventes",
    "reports.products.salesDesc": "Analyse des ventes et performance par produit",
    "reports.products.dateFilters": "Filtres de dates",
    "reports.products.selectPeriodProfit": "Sélectionner une période pour analyser les profits",
    "reports.products.selectPeriodSales": "Sélectionner une période pour analyser les ventes",
    "reports.products.companyFilter": "Filtre par entreprise",
    "reports.products.companyFilterDesc": "Filtrer par entreprise (optionnel)",
    "reports.products.filterType": "Type de filtre",
    "reports.products.selectFilterType": "Sélectionner le type de filtre",
    "reports.products.allCompanies": "Toutes les entreprises",
    "reports.products.byCompany": "Par entreprise",
    "reports.products.company": "Entreprise",
    "reports.products.selectCompany": "Sélectionner une entreprise",
    "reports.products.loadingProfit": "Chargement des données de profit...",
    "reports.products.loadingSales": "Chargement des données de ventes...",
    "reports.products.totalProfit": "Profit total",
    "reports.products.totalRevenue": "Revenu total",
    "reports.products.totalCost": "Coût total",
    "reports.products.overallMargin": "Marge globale",
    "reports.products.profitByProduct": "Profit par produit",
    "reports.products.profitByProductDesc": "Analyse comparative des profits générés par chaque produit",
    "reports.products.productDetails": "Détails des produits",
    "reports.products.productDetailsDesc": "Analyse détaillée de la rentabilité de chaque produit",
    "reports.products.product": "Produit",
    "reports.products.qtySold": "Qté vendue",
    "reports.products.revenue": "Revenu",
    "reports.products.cost": "Coût",
    "reports.products.profit": "Profit",
    "reports.products.marginPercent": "Marge %",
    "reports.products.avgPrice": "Prix moy.",
    "reports.products.noProfitData": "Aucune donnée de profit disponible pour la période sélectionnée.",
    "reports.products.totalProducts": "Total de produits",
    "reports.products.productsInInventory": "produits en inventaire",
    "reports.products.activeProducts": "Produits actifs",
    "reports.products.activeProductsCount": "produits actifs",
    "reports.products.lowStockAlert": "Alerte stock bas",
    "reports.products.productsOutOfStock": "produits en rupture de stock",
    "reports.products.totalInventoryValue": "Valeur totale de l'inventaire",
    "reports.products.totalInventoryValueDesc": "valeur totale de l'inventaire",
    "reports.products.stockLevelsByProduct": "Niveaux de stock par produit",
    "reports.products.stockLevelsDesc": "Quantités disponibles pour chaque produit",
    "reports.products.quantity": "Quantité",
    "reports.products.quantityLabel": "Quantité",
    "reports.products.noProductsFound": "Aucun produit trouvé",
    "reports.products.inventoryDetails": "Détails des produits",
    "reports.products.inventoryDetailsDesc": "Informations complètes sur tous les produits",
    "reports.products.name": "Nom",
    "reports.products.sku": "SKU",
    "reports.products.category": "Catégorie",
    "reports.products.price": "Prix",
    "reports.products.margin": "Marge",
    "reports.products.stockValue": "Valeur du stock",
    "reports.products.status": "Statut",
    "reports.products.active": "Actif",
    "reports.products.inactive": "Inactif",
    "reports.products.totalQuantitySold": "Quantité totale vendue",
    "reports.products.numberOfSales": "Nombre de ventes",
    "reports.products.productsSold": "Produits vendus",
    "reports.products.servicesSold": "Services vendus",
    "reports.products.revenueByProduct": "Revenu par produit",
    "reports.products.revenueByProductDesc": "Analyse de performance des ventes par produits physiques",
    "reports.products.revenueByService": "Revenu par service",
    "reports.products.revenueByServiceDesc": "Analyse de performance des ventes par services",
    "reports.products.salesDetails": "Détails des ventes",
    "reports.products.salesDetailsDesc": "Informations détaillées des ventes pour les produits et services",
    "reports.products.productServiceLabel": "Produit/Service",
    "reports.products.salesCount": "Nombre de ventes",
    "reports.products.firstSale": "Première vente",
    "reports.products.lastSale": "Dernière vente",
    "reports.products.productLabel": "Produit",
    "reports.products.serviceLabel": "Service",
    "reports.products.noSalesData": "Aucune donnée de vente disponible pour la période sélectionnée.",
    "reports.revenue.filterBy": "Filtrer par",
    "reports.revenue.all": "Tous",
    "reports.revenue.company": "Entreprise",
    "reports.revenue.client": "Client",
    "reports.revenue.selectCompany": "Sélectionner une entreprise",
    "reports.revenue.selectClient": "Sélectionner un client",
    "reports.revenue.monthlyRevenue": "Revenus mensuels",
    "reports.revenue.yearlyRevenue": "Revenus annuels",
    "reports.revenue.option1": "Option 1 : Sélectionner une année spécifique",
    "reports.revenue.option2": "Option 2 : Sélectionner une plage d'années",
    "reports.revenue.startYear": "Année de début",
    "reports.revenue.endYear": "Année de fin",
    "reports.revenue.viewMonthly": "Vue mensuelle",
    "reports.revenue.viewYearly": "Vue annuelle",
    "reports.revenue.downloadPDF": "Télécharger PDF",
    "reports.revenue.downloadExcel": "Télécharger Excel",
    "reports.revenue.downloadCharts": "Télécharger les graphiques",
    "reports.revenue.totalRevenue": "Revenu total",
    "reports.revenue.numberOfInvoices": "Nombre de factures",
    "reports.revenue.averageRevenue": "Revenu moyen",
    "reports.revenue.revenueEvolution": "Évolution des revenus par",
    "reports.revenue.revenueTrend": "Tendance des revenus",
    "reports.revenue.detailsByPeriod": "Détails par période",
    "reports.revenue.detailedDataBy": "Données détaillées par",
    "reports.revenue.period": "Période",
    "reports.revenue.revenue": "Revenu",
    "reports.revenue.invoices": "Factures",
    "reports.revenue.averageRevenuePerInvoice": "Revenu moyen par facture",
    "reports.revenue.invoicesList": "Liste des factures",
    "reports.revenue.invoicesListDescription": "Liste détaillée des factures payées dans la période sélectionnée",
    "reports.revenue.invoiceNumber": "Facture n°",
    "reports.revenue.clientName": "Client",
    "reports.revenue.amount": "Montant",
    "reports.revenue.date": "Date",
    "reports.revenue.issueDate": "Date d'émission",
    "reports.revenue.totalAmount": "Montant total",
    "reports.revenue.status": "Statut",
    "reports.revenue.month": "mois",
    "reports.revenue.year": "année",
    "reports.revenue.monthly": "Mensuel",
    "reports.revenue.yearly": "Annuel",
    "reports.products.profitMargin": "Marge bénéficiaire",
    "reports.products.productName": "Produit",
    "reports.products.quantitySold": "Quantité vendue",
    "reports.products.profitDetails": "Détails du profit par produit",
    "reports.products.averageSalePrice": "Prix de vente moyen",
    "reports.products.averageCostPrice": "Prix de coût moyen",
    "reports.products.stockStatus": "État du stock",
    "reports.products.currentStock": "Stock actuel",
    "reports.products.unit": "Unité",
    "reports.products.lowStock": "Stock faible",
    "reports.products.salesByProduct": "Ventes par produit",
    "reports.products.salesByService": "Ventes par service",
    "reports.products.services": "Services",
    "reports.expenses.dateFilters": "Filtres de dates",
    "reports.expenses.filters": "Filtres",
    "reports.expenses.filterBy": "Filtrer par",
    "reports.expenses.selectCategory": "Sélectionner une catégorie",
    "reports.expenses.totalExpenses": "Total des dépenses",
    "reports.expenses.expensesByCategory": "Dépenses par catégorie",
    "reports.expenses.expensesByCompany": "Dépenses par entreprise",
    "reports.expenses.amount": "Montant",
    "reports.expenses.expenseDetails": "Détails des dépenses",
    "reports.expenses.descriptionField": "Description",
    "reports.expenses.date": "Date",
    "reports.expenses.vendor": "Fournisseur",
    "reports.expenses.dateRange": "Plage de dates",
    "reports.expenses.filterType": "Type de filtre",
    "reports.expenses.selectFilterType": "Sélectionner le type de filtre",
    "reports.expenses.allExpenses": "Toutes les dépenses",
    "reports.expenses.byCompanyFilter": "Par compagnie",
    "reports.expenses.byCategoryFilter": "Par catégorie",
    "reports.expenses.selectCompany": "Sélectionner une compagnie",
    "reports.expenses.paidExpenses": "Dépenses payées",
    "reports.expenses.unpaidExpenses": "Dépenses impayées",
    "reports.expenses.noData": "Aucune donnée de dépense disponible",
    "reports.expenses.loading": "Chargement des données de dépenses...",
    "reports.expenses.filtersCriteria": "Sélectionnez les critères pour filtrer les dépenses",
    "reports.expenses.allExpensesDetail": "Détail de toutes les dépenses",
    "reports.expenses.allExpensesDetailDesc": "Liste complète des dépenses avec leurs taxes",
    "reports.expenses.taxes": "Taxes",
    "reports.expenses.total": "Total",
    "reports.expenses.status": "Statut",
    "reports.expenses.paid": "Payé",
    "reports.expenses.unpaid": "Impayé",
    "reports.expenses.noCategoryData": "Aucune donnée de catégorie disponible",
    "reports.clients.title": "Rapport des clients",
    "reports.clients.description": "Liste des clients par compagnie et statistiques",
    "reports.clients.filters": "Filtres",
    "reports.clients.filterDescription": "Filtrer les clients par date de création",
    "reports.clients.createdFromDate": "Date de création (du)",
    "reports.clients.createdToDate": "Date de création (au)",
    "reports.clients.selectDate": "Sélectionner une date",
    "reports.clients.clearFilters": "Effacer les filtres",
    "reports.clients.allClients": "Tous les clients",
    "reports.clients.allClientsDescription": "Liste complète de tous les clients",
    "reports.clients.clientName": "Nom du client",
    "reports.clients.company": "Compagnie",
    "reports.clients.contactPerson": "Personne de contact",
    "reports.clients.creationDate": "Date de création",
    "reports.clients.noCompany": "Aucune compagnie",
    "reports.clients.noClientsFound": "Aucun client trouvé pour cette période",
    "reports.clients.clientsByCompany": "Clients par compagnie",
    "reports.clients.clientsByCompanyDesc": "Répartition des clients selon leurs compagnies",
    "reports.clients.clientCount": "client",
    "reports.clients.clientCountPlural": "clients",
    "reports.clients.noClientsForCompany": "Aucun client associé à cette compagnie",
    "reports.clients.clientsWithoutCompany": "Clients sans compagnie assignée",
    "reports.clients.dateFilters": "Filtres de dates",
    "reports.clients.createdFrom": "Créé à partir du",
    "reports.clients.createdTo": "Créé jusqu'au",
    "reports.clients.totalClients": "Total de clients",
    "reports.clients.clientsList": "Liste des clients",
    "reports.clients.name": "Nom",
    "reports.clients.email": "Email",
    "reports.clients.phone": "Téléphone",
    "reports.clients.totalInvoiced": "Total facturé",
    "reports.clients.lastInvoice": "Dernière facture",
    "reports.clients.createdOn": "Créé le",
    "reports.clients.noInvoice": "Aucune facture",
    "reports.taxes.dateRange": "Plage de dates",
    "reports.taxes.selectMonth": "Sélectionner un mois",
    "reports.taxes.selectYear": "Sélectionner une année",
    "reports.taxes.companyFilter": "Filtre par entreprise",
    "reports.taxes.allCompanies": "Toutes les entreprises",
    "reports.taxes.taxSummary": "Résumé des taxes",
    "reports.taxes.totalTaxCollected": "Total de taxes perçues",
    "reports.taxes.totalRevenue": "Revenu total",
    "reports.taxes.taxesByRate": "Taxes par taux",
    "reports.taxes.taxRate": "Taux de taxe",
    "reports.taxes.taxAmount": "Montant de la taxe",
    "reports.taxes.taxDetails": "Détails des taxes par période",
    "reports.taxes.invoicesWithTax": "Factures avec taxes",
    "reports.taxes.filters": "Filtres du rapport de taxes",
    "reports.taxes.company": "Compagnie",
    "reports.taxes.periodType": "Type de période",
    "reports.taxes.customDates": "Dates personnalisées",
    "reports.taxes.byMonth": "Par mois",
    "reports.taxes.byYear": "Par année",
    "reports.taxes.display": "Affichage",
    "reports.taxes.monthly": "Mensuel",
    "reports.taxes.yearly": "Annuel",
    "reports.taxes.startDate": "Date de début",
    "reports.taxes.endDate": "Date de fin",
    "reports.taxes.select": "Sélectionner",
    "reports.taxes.month": "Mois",
    "reports.taxes.year": "Année",
    "reports.taxes.grandTotal": "Total général des taxes",
    "reports.taxes.totalByType": "Total par type de taxe",
    "reports.taxes.invoice": "facture",
    "reports.taxes.invoices": "factures",
    "reports.taxes.distribution": "Répartition des taxes",
    "reports.taxes.amount": "Montant",
    "reports.taxes.taxesAmount": "Montant des taxes",
    "reports.taxes.evolutionBy": "Évolution des taxes par",
    "reports.taxes.noData": "Aucune donnée de taxes",
    "reports.taxes.noDataDesc": "Aucune facture payée avec taxes trouvée pour cette période.",
    "reports.taxes.summaryCollected": "Résumé des taxes collectées",
    "reports.taxes.summaryDesc": "Vue d'ensemble des taxes par type",
    "reports.taxes.taxType": "Type de taxe",
    "reports.taxes.totalAmount": "Montant total",
    "reports.taxes.invoiceCount": "Nombre de factures",
    "reports.taxes.detailBy": "Détail des taxes par",
    "reports.taxes.period": "Période",
    "reports.taxes.totalTaxes": "Total taxes",
    "reports.taxes.invoicesLabel": "Factures",
    "reports.taxes.detailByTax": "Détail par taxe",
    "reports.taxes.download": "Téléchargement",
    "reports.taxes.exportDesc": "Exporter le rapport de taxes",
    
    // PDF Reports
    "reports.pdf.allPeriods": "Toutes les périodes",
    "reports.pdf.since": "Depuis le",
    "reports.pdf.until": "Jusqu'au",
    "reports.pdf.period": "Période",
    "reports.pdf.allCompanies": "Toutes les compagnies",
    "reports.pdf.company": "Compagnie",
    "reports.pdf.reportDate": "Date du rapport",
    "reports.pdf.totalProducts": "Total de produits",
    "reports.pdf.activeProducts": "Produits actifs",
    "reports.pdf.lowStockAlerts": "Alertes stock bas",
    "reports.pdf.totalInventoryValue": "Valeur totale de l'inventaire",
    "reports.pdf.summary": "Résumé",
    "reports.pdf.salesReport": "Rapport des ventes",
    "reports.pdf.productProfitReport": "Rapport des profits par produit",
    "reports.pdf.inventoryReport": "Rapport d'inventaire",
    "reports.pdf.expenseReport": "Rapport des dépenses",
    "reports.pdf.clientReport": "Rapport des clients",
    "reports.pdf.revenueByProductChart": "Graphique - Revenu par produit",
    "reports.pdf.revenueByServiceChart": "Graphique - Revenu par service",
    "reports.pdf.salesDetails": "Détails des ventes",
    "reports.pdf.profitByProductChart": "Graphique - Profit par produit",
    "reports.pdf.productDetails": "Détails des produits",
    
    
    // Settings
    "settings.title": "Paramètres",
    "settings.description": "Gérez les paramètres de votre compte",
    "settings.account.title": "Informations du compte",
    "settings.account.description": "Vos informations personnelles",
    "settings.account.email": "Email",
    "settings.account.username": "Nom d'utilisateur",
    "settings.account.usernamePlaceholder": "Entrez votre nom d'utilisateur",
    "settings.account.usernameDescription": "Votre nom d'utilisateur unique pour le compte",
    "settings.account.save": "Enregistrer",
    "settings.account.saving": "Enregistrement...",
    "settings.account.usernameUpdated": "Nom d'utilisateur mis à jour",
    "settings.account.usernameUpdatedDescription": "Votre nom d'utilisateur a été mis à jour avec succès",
    "settings.account.usernameError": "Erreur lors de la mise à jour du nom d'utilisateur",
    "settings.appearance.title": "Apparence",
    "settings.appearance.description": "Personnalisez l'apparence de l'application selon vos préférences",
    "settings.appearance.displayMode": "Mode d'affichage",
    "settings.appearance.light": "Clair",
    "settings.appearance.dark": "Sombre",
    "settings.appearance.colorTheme": "Thème de couleur",
    "settings.appearance.classic": "Classique (Bleu)",
    "settings.appearance.modern": "Moderne (Violet)",
    "settings.appearance.warm": "Chaleureux (Orange)",
    "settings.appearance.nature": "Nature (Vert)",
    "settings.language.title": "Langue",
    "settings.language.description": "Choisissez votre langue préférée",
    "settings.language.english": "English",
    "settings.language.french": "Français",
    "settings.invoice.title": "Design de facture",
    "settings.invoice.description": "Choisissez votre modèle de facture préféré",
    "settings.invoice.templateLabel": "Modèle de facture",
    "settings.invoice.classic": "Classique",
    "settings.invoice.modern": "Moderne",
    "settings.invoice.professional": "Professionnel",
    "settings.invoice.creative": "Créatif",
    "settings.invoice.colorLabel": "Couleur de facture",
    "settings.invoice.blue": "Bleu",
    "settings.invoice.green": "Vert",
    "settings.invoice.purple": "Violet",
    "settings.invoice.orange": "Orange",
    "settings.invoice.yellow": "Jaune",
    "settings.invoice.gray": "Gris",
    "settings.invoice.preview": "Aperçu",
    
    // Password Change
    "password.title": "Changer le mot de passe",
    "password.description": "Modifiez votre mot de passe pour sécuriser votre compte",
    "password.new": "Nouveau mot de passe",
    "password.confirm": "Confirmer le nouveau mot de passe",
    "password.button": "Changer le mot de passe",
    "password.updating": "Modification en cours...",
    "password.error.length": "Le nouveau mot de passe doit contenir au moins 6 caractères",
    "password.error.match": "Les mots de passe ne correspondent pas",
    "password.success.title": "Succès",
    "password.success.description": "Votre mot de passe a été modifié avec succès.",
    "password.error.title": "Erreur",
    
    // Auth
    "auth.title": "Gestion d'Entreprise",
    "auth.subtitle": "Connectez-vous à votre compte ou créez-en un nouveau",
    "auth.signIn": "Se connecter",
    "auth.signUp": "S'inscrire",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.signingIn": "Connexion en cours...",
    "auth.displayName": "Nom d'affichage",
    "auth.creatingAccount": "Création du compte...",
    "auth.createAccount": "Créer un compte",
    "auth.forgotPassword": "Mot de passe oublié ?",
    "auth.signInFailed": "Échec de la connexion",
    "auth.welcomeBack": "Bon retour !",
    "auth.signInSuccess": "Vous vous êtes connecté avec succès.",
    "auth.signUpFailed": "Échec de l'inscription",
    "auth.accountCreated": "Compte créé !",
    "auth.checkEmail": "Veuillez vérifier votre email pour valider votre compte.",
    "auth.displayNameRequired": "Le nom d'affichage est requis",
    "auth.resetPassword": "Réinitialiser le mot de passe",
    "auth.resetPasswordDesc": "Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.",
    "auth.resetFailed": "Échec de la réinitialisation",
    "auth.resetEmailSent": "Email de réinitialisation envoyé !",
    "auth.checkResetEmail": "Veuillez vérifier votre email pour les instructions de réinitialisation.",
    "auth.sending": "Envoi en cours...",
    "auth.sendResetLink": "Envoyer le lien de réinitialisation",
    "auth.updatePassword": "Mettre à jour le mot de passe",
    "auth.updatePasswordDesc": "Entrez votre nouveau mot de passe ci-dessous.",
    "auth.newPassword": "Nouveau mot de passe",
    "auth.confirmPassword": "Confirmer le mot de passe",
    "auth.updating": "Mise à jour...",
    "auth.updateFailed": "Échec de la mise à jour",
    "auth.passwordUpdated": "Mot de passe mis à jour !",
    "auth.passwordUpdateSuccess": "Votre mot de passe a été mis à jour avec succès.",
    "auth.passwordsDoNotMatch": "Les mots de passe ne correspondent pas",
    "auth.passwordTooShort": "Le mot de passe doit contenir au moins 6 caractères",
    "auth.cancel": "Annuler",
    
    // PWA Install Banner
    "pwa.install.title": "Installer GestionFlow",
    "pwa.install.description": "Ajoutez à votre bureau pour un accès rapide et une utilisation hors ligne.",
    "pwa.install.button": "Installer",
    "pwa.install.later": "Plus tard",
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("app-language") as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "fr")) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string, replacements?: Record<string, string | number>): string => {
    let translation = translations[language][key as keyof typeof translations.en] || key;
    
    // Replace placeholders with actual values
    if (replacements) {
      Object.entries(replacements).forEach(([placeholder, value]) => {
        translation = translation.replace(`{${placeholder}}`, String(value));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
