import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface SendReportEmailRequest {
  recipientEmail: string;
  reportTitle: string;
  reportType: string;
  message?: string;
  pdfBase64: string;
  language: string;
}

const logStep = (step: string, details?: any) => {
  const detailsStr = details ? ` - ${JSON.stringify(details)}` : '';
  console.log(`[SEND-REPORT-EMAIL] ${step}${detailsStr}`);
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    logStep("Function started");

    const resendApiKey = Deno.env.get("RESEND_API_KEY");
    const fromEmail = Deno.env.get("RESEND_FROM") || "GestionFlow <noreply@gestionflow.net>";
    
    if (!resendApiKey) {
      throw new Error("RESEND_API_KEY is not configured");
    }

    const { 
      recipientEmail, 
      reportTitle, 
      reportType, 
      message, 
      pdfBase64, 
      language 
    } = await req.json() as SendReportEmailRequest;

    logStep("Request data", { recipientEmail, reportTitle, reportType, language });

    // Validate inputs
    if (!recipientEmail || !reportTitle || !pdfBase64) {
      throw new Error("Missing required fields");
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(recipientEmail)) {
      throw new Error("Invalid email format");
    }

    const isFrench = language === 'fr';
    const resend = new Resend(resendApiKey);

    // Generate filename
    const date = new Date().toISOString().split('T')[0];
    const sanitizedTitle = reportTitle.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();
    const filename = `${sanitizedTitle}-${date}.pdf`;

    // Email subject
    const subject = isFrench 
      ? `Rapport GestionFlow : ${reportTitle}`
      : `GestionFlow Report: ${reportTitle}`;

    // Email body
    const customMessageHtml = message 
      ? `<div style="background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #2563eb;">
           <p style="margin: 0; color: #333; white-space: pre-wrap;">${message}</p>
         </div>`
      : '';

    const emailHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9fafb;">
          <div style="background: white; padding: 30px; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
            <!-- Header -->
            <div style="text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #e5e7eb;">
              <h1 style="color: #1f2937; margin: 0; font-size: 24px;">
                ${isFrench ? 'Rapport' : 'Report'}: ${reportTitle}
              </h1>
              <p style="color: #6b7280; margin: 10px 0 0 0; font-size: 14px;">
                ${isFrench ? 'Généré par GestionFlow' : 'Generated by GestionFlow'}
              </p>
            </div>

            <!-- Greeting -->
            <p style="color: #374151; font-size: 16px; line-height: 1.6;">
              ${isFrench ? 'Bonjour,' : 'Hello,'}
            </p>

            ${customMessageHtml}

            <!-- Main content -->
            <p style="color: #374151; font-size: 16px; line-height: 1.6;">
              ${isFrench 
                ? `Veuillez trouver ci-joint le rapport "<strong>${reportTitle}</strong>" en format PDF.`
                : `Please find attached the "<strong>${reportTitle}</strong>" report in PDF format.`}
            </p>

            <!-- Report info box -->
            <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin: 25px 0; border: 1px solid #bae6fd;">
              <table style="width: 100%; border-collapse: collapse;">
                <tr>
                  <td style="padding: 8px 0; color: #64748b; font-size: 14px;">
                    ${isFrench ? 'Type de rapport' : 'Report Type'}:
                  </td>
                  <td style="padding: 8px 0; color: #1e40af; font-weight: 600; text-align: right; font-size: 14px;">
                    ${reportTitle}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; color: #64748b; font-size: 14px;">
                    ${isFrench ? 'Date de génération' : 'Generation Date'}:
                  </td>
                  <td style="padding: 8px 0; color: #1e40af; font-weight: 600; text-align: right; font-size: 14px;">
                    ${new Date().toLocaleDateString(isFrench ? 'fr-FR' : 'en-US', { 
                      year: 'numeric', 
                      month: 'long', 
                      day: 'numeric' 
                    })}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; color: #64748b; font-size: 14px;">
                    ${isFrench ? 'Fichier joint' : 'Attachment'}:
                  </td>
                  <td style="padding: 8px 0; color: #1e40af; font-weight: 600; text-align: right; font-size: 14px;">
                    📎 ${filename}
                  </td>
                </tr>
              </table>
            </div>

            <!-- Footer -->
            <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center;">
              <p style="color: #9ca3af; font-size: 12px; margin: 0;">
                ${isFrench 
                  ? 'Ce courriel a été envoyé automatiquement par GestionFlow.'
                  : 'This email was automatically sent by GestionFlow.'}
              </p>
              <p style="color: #9ca3af; font-size: 12px; margin: 5px 0 0 0;">
                © ${new Date().getFullYear()} GestionFlow - ${isFrench ? 'Tous droits réservés' : 'All rights reserved'}
              </p>
            </div>
          </div>
        </body>
      </html>
    `;

    // Convert base64 to buffer for attachment
    const pdfBuffer = Uint8Array.from(atob(pdfBase64), c => c.charCodeAt(0));

    // Send email with PDF attachment
    const emailResult = await resend.emails.send({
      from: fromEmail,
      to: [recipientEmail],
      subject: subject,
      html: emailHtml,
      attachments: [
        {
          filename: filename,
          content: pdfBuffer,
        },
      ],
    });

    logStep("Email sent successfully", { id: emailResult.data?.id });

    return new Response(
      JSON.stringify({ success: true, message: "Report email sent successfully" }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 200 }
    );
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    logStep("ERROR", { message: errorMessage });
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500 }
    );
  }
});
