// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { fetch as tauriFetch } from '@tauri-apps/plugin-http';
import type { Database } from './types';

const SUPABASE_URL = "https://dkinzkawntfzkabroeib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRraW56a2F3bnRmemthYnJvZWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODEzNTksImV4cCI6MjA2NzY1NzM1OX0.KATTnChUgaAnxvscEecoi8arzSvTKWfsqUZdLSg7EpY";

const isTauriRuntime = typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;
const supabaseFetch = isTauriRuntime ? tauriFetch : globalThis.fetch.bind(globalThis);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    // WebView2 can reject cross-origin Supabase requests while the same URL
    // works in Chromium. Tauri's HTTP plugin performs the request natively.
    fetch: supabaseFetch,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
